/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CompAiCore } from "../core.js";
import { appendForm, normalizeBlob } from "../lib/encodings.js";
import {
  bytesToBlob,
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  QuestionnaireControllerParseQuestionnaireUploadV1Request,
  QuestionnaireControllerParseQuestionnaireUploadV1Request$zodSchema,
  QuestionnaireControllerParseQuestionnaireUploadV1Security,
} from "../models/questionnairecontrollerparsequestionnaireuploadv1op.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Auto-answer uploaded questionnaire
 *
 * @remarks
 * Upload a questionnaire file and generate answer exports from approved organization evidence in PDF, CSV, or XLSX format.
 */
export function questionnaireQuestionnaireControllerParseQuestionnaireUploadV1(
  client$: CompAiCore,
  security: QuestionnaireControllerParseQuestionnaireUploadV1Security,
  request: QuestionnaireControllerParseQuestionnaireUploadV1Request,
  options?: RequestOptions,
): APIPromise<
  Result<
    Response,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    security,
    request,
    options,
  ));
}

async function $do(
  client$: CompAiCore,
  security: QuestionnaireControllerParseQuestionnaireUploadV1Security,
  request: QuestionnaireControllerParseQuestionnaireUploadV1Request,
  options?: RequestOptions,
): Promise<
  [
    Result<
      Response,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) =>
      QuestionnaireControllerParseQuestionnaireUploadV1Request$zodSchema.parse(
        value$,
      ),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = new FormData();
  if (isBlobLike(payload$.file)) {
    const file = payload$.file;
    const blob = await normalizeBlob(file);
    const name = "name" in file ? (file.name as string) : undefined;
    appendForm(body$, "file", blob, name);
  } else if (isReadableStream(payload$.file.content)) {
    const buffer = await readableStreamToArrayBuffer(payload$.file.content);
    const contentType = getContentTypeFromFileName(payload$.file.fileName)
      || "application/octet-stream";
    appendForm(
      body$,
      "file",
      bytesToBlob(buffer, contentType),
      payload$.file.fileName,
    );
  } else {
    const contentType = getContentTypeFromFileName(payload$.file.fileName)
      || "application/octet-stream";
    appendForm(
      body$,
      "file",
      bytesToBlob(payload$.file.content, contentType),
      payload$.file.fileName,
    );
  }
  appendForm(body$, "organizationId", payload$.organizationId);
  if (payload$.format !== undefined) {
    appendForm(body$, "format", payload$.format);
  }
  if (payload$.source !== undefined) {
    appendForm(body$, "source", payload$.source);
  }
  const path$ = pathToFunc("/v1/questionnaire/parse/upload")();

  const headers$ = new Headers(compactMap({
    Accept: "*/*",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "X-API-Key",
        type: "apiKey:header",
        value: security?.apikey,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "oauth2",
        value: security?.oauth2,
      },
    ],
  );

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "QuestionnaireController_parseQuestionnaireUpload_v1",
    oAuth2Scopes: null,
    resolvedSecurity: requestSecurity,
    securitySource: security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  return [doResult, {
    status: "complete",
    "request": req$,
    response: doResult.value,
  }];
}
