version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    target-branch: 'main'
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    target-branch: 'main'
    open-pull-requests-limit: 3
