/**
 * GCP/Azure check descriptions are NOT generated by AI — they're surfaced
 * directly from the provider's own evidence payload, which already
 * contains auditor-grade descriptions written by Google / Microsoft.
 *
 * This module isolates the per-provider mapping so the main
 * CheckDefinitionService stays focused on cache + AI orchestration.
 */

import type { ResolvedCheckDescription } from './check-definition.service';

export interface PassthroughInput {
  provider: 'gcp' | 'azure' | string;
  title: string;
  description: string | null;
  evidence: Record<string, unknown> | null;
}

function humanizeCategory(category: string): string {
  return category
    .toLowerCase()
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function fromGcpEvidence(
  input: PassthroughInput,
): ResolvedCheckDescription | null {
  if (!input.evidence) return null;
  const category =
    typeof input.evidence.category === 'string'
      ? input.evidence.category
      : null;
  const findingClass =
    typeof input.evidence.findingClass === 'string'
      ? input.evidence.findingClass
      : null;
  if (!category) return null;

  const humanCategory = humanizeCategory(category);

  // Each of the four fields needs a genuinely different sentence — auditors
  // shouldn't see the same paragraph three times under different labels.
  // Derived from the category code (stable, machine-readable), not from
  // SCC's per-finding `description` (which is generic category info that
  // duplicates across fields when used naively).
  return {
    title: input.title,
    description: `This check surfaces findings from Google Security Command Center under the "${humanCategory}" detector. SCC continuously evaluates your projects against Google's security baseline and flags resources matching the ${category} pattern.`,
    passCriteria: `Google Security Command Center reports no active "${humanCategory}" findings for this project.`,
    failCriteria: `Google Security Command Center detected a resource matching the "${humanCategory}" criteria in this project.`,
    whyItMatters: findingClass
      ? `Google classifies this finding as a ${findingClass.toLowerCase()} — addressing it reduces the underlying security risk Google identified for the ${humanCategory} category.`
      : `Findings under the ${humanCategory} category indicate a security concern Google detected in the customer environment.`,
    source: 'provider',
  };
}

function fromAzureEvidence(
  input: PassthroughInput,
): ResolvedCheckDescription | null {
  const alertType =
    input.evidence && typeof input.evidence.alertType === 'string'
      ? input.evidence.alertType
      : input.evidence && typeof input.evidence.serviceName === 'string'
        ? (input.evidence.serviceName as string)
        : null;

  const subject = alertType ?? 'this configuration';

  return {
    title: input.title,
    description: `This check surfaces findings from Microsoft Defender for Cloud${alertType ? ` under the "${alertType}" assessment` : ''}. Defender continuously evaluates the subscription against Microsoft's secure-configuration baseline and flags resources that diverge from the recommended state.`,
    passCriteria: `Microsoft Defender for Cloud reports ${subject} as healthy on this subscription.`,
    failCriteria: `Microsoft Defender for Cloud reports ${subject} as unhealthy on this resource.`,
    whyItMatters: alertType
      ? `Defender raised this finding under "${alertType}" — addressing it brings the resource in line with Microsoft's recommended configuration.`
      : 'Defender for Cloud findings indicate a deviation from Microsoft-recommended secure configuration in the customer environment.',
    source: 'provider',
  };
}

export function buildProviderPassthroughDescription(
  input: PassthroughInput,
): ResolvedCheckDescription | null {
  if (input.provider === 'gcp') return fromGcpEvidence(input);
  if (input.provider === 'azure') return fromAzureEvidence(input);
  return null;
}
