/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Available scopes for the oauth2 OAuth 2.0 scheme (authorizationCode flow).
 *
 * @remarks
 * OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.
 */
export type OAuth2Scope =
  /**
   * OpenID Connect authentication
   */
  | "openid"
  /**
   * Basic profile information
   */
  | "profile"
  /**
   * Email address
   */
  | "email"
  /**
   * Maintain access via refresh tokens
   */
  | "offline_access";
