/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AttachmentResponseDto,
  AttachmentResponseDto$zodSchema,
} from "./attachmentresponsedto.js";

/**
 * Unauthorized - Invalid authentication
 */
export type AttachmentsControllerCreateAttachmentV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const AttachmentsControllerCreateAttachmentV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<AttachmentsControllerCreateAttachmentV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized - Invalid authentication");

/**
 * Invalid file data, unsupported file type, or file too large
 */
export type AttachmentsControllerCreateAttachmentV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const AttachmentsControllerCreateAttachmentV1BadRequestResponseBody$zodSchema:
  z.ZodType<AttachmentsControllerCreateAttachmentV1BadRequestResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Invalid file data, unsupported file type, or file too large");

export type AttachmentsControllerCreateAttachmentV1Response =
  | AttachmentResponseDto
  | AttachmentsControllerCreateAttachmentV1BadRequestResponseBody
  | AttachmentsControllerCreateAttachmentV1UnauthorizedResponseBody;

export const AttachmentsControllerCreateAttachmentV1Response$zodSchema:
  z.ZodType<AttachmentsControllerCreateAttachmentV1Response> = z.union([
    AttachmentResponseDto$zodSchema,
    z.lazy(() =>
      AttachmentsControllerCreateAttachmentV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      AttachmentsControllerCreateAttachmentV1UnauthorizedResponseBody$zodSchema
    ),
  ]);
