/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AuditorEvidenceExportControllerExportAllEvidenceV1Request = {
  includeJson?: boolean | undefined;
};

export const AuditorEvidenceExportControllerExportAllEvidenceV1Request$zodSchema:
  z.ZodType<AuditorEvidenceExportControllerExportAllEvidenceV1Request> = z
    .object({
      includeJson: z.boolean().describe("Include raw JSON files alongside PDFs")
        .optional(),
    });
