/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AutomationsControllerGetAutomationRunsV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const AutomationsControllerGetAutomationRunsV1Security$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationRunsV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type AutomationsControllerGetAutomationRunsV1Request = {
  taskId: string;
  automationId: string;
};

export const AutomationsControllerGetAutomationRunsV1Request$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationRunsV1Request> = z.object({
    automationId: z.string().describe("Automation ID"),
    taskId: z.string().describe("Task ID"),
  });
