/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateAutomationDto,
  UpdateAutomationDto$zodSchema,
} from "./updateautomationdto.js";

export type AutomationsControllerUpdateAutomationV1Request = {
  taskId: string;
  automationId: string;
  body: UpdateAutomationDto;
};

export const AutomationsControllerUpdateAutomationV1Request$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Request> = z.object({
    automationId: z.string().describe("Unique automation identifier"),
    body: UpdateAutomationDto$zodSchema,
    taskId: z.string().describe("Unique task identifier"),
  });

/**
 * Automation not found
 */
export type AutomationsControllerUpdateAutomationV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerUpdateAutomationV1NotFoundResponseBody$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Automation not found");

/**
 * Unauthorized - Invalid authentication
 */
export type AutomationsControllerUpdateAutomationV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerUpdateAutomationV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized - Invalid authentication");

/**
 * Bad request - Invalid automation ID or data
 */
export type AutomationsControllerUpdateAutomationV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerUpdateAutomationV1BadRequestResponseBody$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1BadRequestResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Bad request - Invalid automation ID or data");

export type AutomationsControllerUpdateAutomationV1Automation = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
};

export const AutomationsControllerUpdateAutomationV1Automation$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Automation> = z.object({
    description: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
  });

/**
 * Automation updated successfully
 */
export type AutomationsControllerUpdateAutomationV1ResponseBody = {
  success?: boolean | undefined;
  automation?: AutomationsControllerUpdateAutomationV1Automation | undefined;
};

export const AutomationsControllerUpdateAutomationV1ResponseBody$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1ResponseBody> = z.object({
    automation: z.lazy(() =>
      AutomationsControllerUpdateAutomationV1Automation$zodSchema
    ).optional(),
    success: z.boolean().optional(),
  }).describe("Automation updated successfully");

export type AutomationsControllerUpdateAutomationV1Response =
  | AutomationsControllerUpdateAutomationV1ResponseBody
  | AutomationsControllerUpdateAutomationV1BadRequestResponseBody
  | AutomationsControllerUpdateAutomationV1UnauthorizedResponseBody
  | AutomationsControllerUpdateAutomationV1NotFoundResponseBody;

export const AutomationsControllerUpdateAutomationV1Response$zodSchema:
  z.ZodType<AutomationsControllerUpdateAutomationV1Response> = z.union([
    z.lazy(() => AutomationsControllerUpdateAutomationV1ResponseBody$zodSchema),
    z.lazy(() =>
      AutomationsControllerUpdateAutomationV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      AutomationsControllerUpdateAutomationV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      AutomationsControllerUpdateAutomationV1NotFoundResponseBody$zodSchema
    ),
  ]);
