/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AutomationsControllerGetAutomationVersionsV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const AutomationsControllerGetAutomationVersionsV1Security$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type AutomationsControllerGetAutomationVersionsV1Request = {
  taskId: string;
  automationId: string;
  limit: string;
  offset: string;
};

export const AutomationsControllerGetAutomationVersionsV1Request$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Request> = z.object({
    automationId: z.string().describe("Automation ID"),
    limit: z.string(),
    offset: z.string(),
    taskId: z.string().describe("Task ID"),
  });

export type AutomationsControllerGetAutomationVersionsV1Version = {
  id?: string | undefined;
  version?: number | undefined;
  scriptKey?: string | undefined;
  changelog?: string | null | undefined;
  publishedBy?: string | null | undefined;
  createdAt?: string | undefined;
};

export const AutomationsControllerGetAutomationVersionsV1Version$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Version> = z.object({
    changelog: z.string().nullable().optional(),
    createdAt: z.iso.datetime({ offset: true }).optional(),
    id: z.string().optional(),
    publishedBy: z.string().nullable().optional(),
    scriptKey: z.string().optional(),
    version: z.number().optional(),
  });

/**
 * Versions retrieved successfully
 */
export type AutomationsControllerGetAutomationVersionsV1Response = {
  success?: boolean | undefined;
  versions?:
    | Array<AutomationsControllerGetAutomationVersionsV1Version>
    | undefined;
};

export const AutomationsControllerGetAutomationVersionsV1Response$zodSchema:
  z.ZodType<AutomationsControllerGetAutomationVersionsV1Response> = z.object({
    success: z.boolean().optional(),
    versions: z.array(
      z.lazy(() =>
        AutomationsControllerGetAutomationVersionsV1Version$zodSchema
      ),
    ).optional(),
  }).describe("Versions retrieved successfully");
