/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AutomationsControllerCreateAutomationV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1Security$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type AutomationsControllerCreateAutomationV1Request = { taskId: string };

export const AutomationsControllerCreateAutomationV1Request$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Request> = z.object({
    taskId: z.string().describe("Unique task identifier"),
  });

/**
 * Task not found
 */
export type AutomationsControllerCreateAutomationV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1NotFoundResponseBody$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Task not found");

/**
 * Unauthorized - Invalid authentication
 */
export type AutomationsControllerCreateAutomationV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized - Invalid authentication");

/**
 * Bad request - Invalid task ID or organization ID
 */
export type AutomationsControllerCreateAutomationV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1BadRequestResponseBody$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1BadRequestResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Bad request - Invalid task ID or organization ID");

export type AutomationsControllerCreateAutomationV1Automation = {
  id?: string | undefined;
  name?: string | undefined;
};

export const AutomationsControllerCreateAutomationV1Automation$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Automation> = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
  });

/**
 * Automation created successfully
 */
export type AutomationsControllerCreateAutomationV1ResponseBody = {
  success?: boolean | undefined;
  automation?: AutomationsControllerCreateAutomationV1Automation | undefined;
};

export const AutomationsControllerCreateAutomationV1ResponseBody$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1ResponseBody> = z.object({
    automation: z.lazy(() =>
      AutomationsControllerCreateAutomationV1Automation$zodSchema
    ).optional(),
    success: z.boolean().optional(),
  }).describe("Automation created successfully");

export type AutomationsControllerCreateAutomationV1Response =
  | AutomationsControllerCreateAutomationV1ResponseBody
  | AutomationsControllerCreateAutomationV1BadRequestResponseBody
  | AutomationsControllerCreateAutomationV1UnauthorizedResponseBody
  | AutomationsControllerCreateAutomationV1NotFoundResponseBody;

export const AutomationsControllerCreateAutomationV1Response$zodSchema:
  z.ZodType<AutomationsControllerCreateAutomationV1Response> = z.union([
    z.lazy(() => AutomationsControllerCreateAutomationV1ResponseBody$zodSchema),
    z.lazy(() =>
      AutomationsControllerCreateAutomationV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      AutomationsControllerCreateAutomationV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      AutomationsControllerCreateAutomationV1NotFoundResponseBody$zodSchema
    ),
  ]);
