/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AutoFillSOADto = {};

export const AutoFillSOADto$zodSchema: z.ZodType<AutoFillSOADto> = z.object({});
