/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ChecksControllerRunSingleCheckV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const ChecksControllerRunSingleCheckV1Security$zodSchema: z.ZodType<
  ChecksControllerRunSingleCheckV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type ChecksControllerRunSingleCheckV1Request = {
  connectionId: string;
  checkId: string;
};

export const ChecksControllerRunSingleCheckV1Request$zodSchema: z.ZodType<
  ChecksControllerRunSingleCheckV1Request
> = z.object({
  checkId: z.string(),
  connectionId: z.string(),
});
