/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CloudSecurityControllerDetectServicesV1Request = {
  connectionId: string;
};

export const CloudSecurityControllerDetectServicesV1Request$zodSchema:
  z.ZodType<CloudSecurityControllerDetectServicesV1Request> = z.object({
    connectionId: z.string(),
  });
