/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MarkExceptionDto,
  MarkExceptionDto$zodSchema,
} from "./markexceptiondto.js";

export type CloudSecurityControllerMarkFindingAsExceptionV1Request = {
  findingId: string;
  body: MarkExceptionDto;
};

export const CloudSecurityControllerMarkFindingAsExceptionV1Request$zodSchema:
  z.ZodType<CloudSecurityControllerMarkFindingAsExceptionV1Request> = z.object({
    body: MarkExceptionDto$zodSchema,
    findingId: z.string(),
  });
