/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateCommentDto,
  UpdateCommentDto$zodSchema,
} from "./updatecommentdto.js";

export type CommentsControllerUpdateCommentV1Request = {
  commentId: string;
  body: UpdateCommentDto;
};

export const CommentsControllerUpdateCommentV1Request$zodSchema: z.ZodType<
  CommentsControllerUpdateCommentV1Request
> = z.object({
  body: UpdateCommentDto$zodSchema,
  commentId: z.string().describe("Unique comment identifier"),
});
