/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Delete comment request body
 */
export type CommentsControllerDeleteCommentV1RequestBody = {
  userId?: string | undefined;
};

export const CommentsControllerDeleteCommentV1RequestBody$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1RequestBody
> = z.object({
  userId: z.string().optional().describe(
    "User ID of the comment author (required for API key auth, ignored for JWT auth)",
  ),
}).describe("Delete comment request body");

export type CommentsControllerDeleteCommentV1Request = {
  commentId: string;
  body: CommentsControllerDeleteCommentV1RequestBody;
};

export const CommentsControllerDeleteCommentV1Request$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1Request
> = z.object({
  body: z.lazy(() => CommentsControllerDeleteCommentV1RequestBody$zodSchema)
    .describe("Delete comment request body"),
  commentId: z.string().describe("Unique comment identifier"),
});

/**
 * Comment not found
 */
export type CommentsControllerDeleteCommentV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const CommentsControllerDeleteCommentV1NotFoundResponseBody$zodSchema:
  z.ZodType<CommentsControllerDeleteCommentV1NotFoundResponseBody> = z.object({
    message: z.string().optional(),
  }).describe("Comment not found");

/**
 * Unauthorized - Invalid authentication
 */
export type CommentsControllerDeleteCommentV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const CommentsControllerDeleteCommentV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<CommentsControllerDeleteCommentV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized - Invalid authentication");

/**
 * Comment deleted successfully
 */
export type CommentsControllerDeleteCommentV1ResponseBody = {
  success?: boolean | undefined;
  deletedCommentId?: string | undefined;
  message?: string | undefined;
};

export const CommentsControllerDeleteCommentV1ResponseBody$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1ResponseBody
> = z.object({
  deletedCommentId: z.string().optional(),
  message: z.string().optional(),
  success: z.boolean().optional(),
}).describe("Comment deleted successfully");

export type CommentsControllerDeleteCommentV1Response =
  | CommentsControllerDeleteCommentV1ResponseBody
  | CommentsControllerDeleteCommentV1UnauthorizedResponseBody
  | CommentsControllerDeleteCommentV1NotFoundResponseBody;

export const CommentsControllerDeleteCommentV1Response$zodSchema: z.ZodType<
  CommentsControllerDeleteCommentV1Response
> = z.union([
  z.lazy(() => CommentsControllerDeleteCommentV1ResponseBody$zodSchema),
  z.lazy(() =>
    CommentsControllerDeleteCommentV1UnauthorizedResponseBody$zodSchema
  ),
  z.lazy(() => CommentsControllerDeleteCommentV1NotFoundResponseBody$zodSchema),
]);
