/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of entity
 */
export const CommentsControllerGetCommentsV1EntityType = {
  Task: "task",
  Vendor: "vendor",
  Risk: "risk",
  Policy: "policy",
  Finding: "finding",
} as const;
/**
 * Type of entity
 */
export type CommentsControllerGetCommentsV1EntityType = ClosedEnum<
  typeof CommentsControllerGetCommentsV1EntityType
>;

export const CommentsControllerGetCommentsV1EntityType$zodSchema = z.enum([
  "task",
  "vendor",
  "risk",
  "policy",
  "finding",
]).describe("Type of entity");

export type CommentsControllerGetCommentsV1Request = {
  entityId: string;
  entityType: CommentsControllerGetCommentsV1EntityType;
};

export const CommentsControllerGetCommentsV1Request$zodSchema: z.ZodType<
  CommentsControllerGetCommentsV1Request
> = z.object({
  entityId: z.string().describe("ID of the entity to get comments for"),
  entityType: CommentsControllerGetCommentsV1EntityType$zodSchema.describe(
    "Type of entity",
  ),
});
