/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ComplianceResourceUrlResponseDto = {
  signedUrl: string;
  fileName: string;
  fileSize: number;
};

export const ComplianceResourceUrlResponseDto$zodSchema: z.ZodType<
  ComplianceResourceUrlResponseDto
> = z.object({
  fileName: z.string(),
  fileSize: z.number().describe("File size in bytes"),
  signedUrl: z.string(),
});
