/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectionsControllerGetProviderV1Request = { slug: string };

export const ConnectionsControllerGetProviderV1Request$zodSchema: z.ZodType<
  ConnectionsControllerGetProviderV1Request
> = z.object({
  slug: z.string(),
});
