/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectionsControllerPauseConnectionV1Request = { id: string };

export const ConnectionsControllerPauseConnectionV1Request$zodSchema: z.ZodType<
  ConnectionsControllerPauseConnectionV1Request
> = z.object({
  id: z.string(),
});
