/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectionsControllerListProvidersV1Request = {
  activeOnly: string;
};

export const ConnectionsControllerListProvidersV1Request$zodSchema: z.ZodType<
  ConnectionsControllerListProvidersV1Request
> = z.object({
  activeOnly: z.string(),
});
