/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateConnectionDto,
  UpdateConnectionDto$zodSchema,
} from "./updateconnectiondto.js";

export type ConnectionsControllerUpdateConnectionV1Request = {
  id: string;
  body: UpdateConnectionDto;
};

export const ConnectionsControllerUpdateConnectionV1Request$zodSchema:
  z.ZodType<ConnectionsControllerUpdateConnectionV1Request> = z.object({
    body: UpdateConnectionDto$zodSchema,
    id: z.string(),
  });
