/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateContextDto,
  UpdateContextDto$zodSchema,
} from "./updatecontextdto.js";

export type ContextControllerUpdateContextV1Request = {
  id: string;
  body: UpdateContextDto;
};

export const ContextControllerUpdateContextV1Request$zodSchema: z.ZodType<
  ContextControllerUpdateContextV1Request
> = z.object({
  body: UpdateContextDto$zodSchema.describe(
    "Partial context entry data to update",
  ),
  id: z.string().describe("Context entry ID"),
});
