/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreatePolicyVersionDto = {
  sourceVersionId?: string | undefined;
  changelog?: string | undefined;
};

export const CreatePolicyVersionDto$zodSchema: z.ZodType<
  CreatePolicyVersionDto
> = z.object({
  changelog: z.string().optional().describe(
    "Optional changelog to associate with the new version",
  ),
  sourceVersionId: z.string().optional().describe(
    "Optional version ID to base the new version on",
  ),
});
