/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateCustomRequirementDto = {
  name: string;
  identifier: string;
  description: string;
};

export const CreateCustomRequirementDto$zodSchema: z.ZodType<
  CreateCustomRequirementDto
> = z.object({
  description: z.string().describe("Description"),
  identifier: z.string().describe("Identifier"),
  name: z.string().describe("Requirement name"),
});
