/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of entity the attachment belongs to
 */
export const CreateAttachmentDtoEntityType = {
  Task: "task",
  Vendor: "vendor",
  Risk: "risk",
  Comment: "comment",
  TrustNda: "trust_nda",
  TaskItem: "task_item",
  BackgroundCheck: "background_check",
  EmploymentOnboard: "employment_onboard",
  EmploymentOffboard: "employment_offboard",
  OffboardingChecklist: "offboarding_checklist",
} as const;
/**
 * Type of entity the attachment belongs to
 */
export type CreateAttachmentDtoEntityType = ClosedEnum<
  typeof CreateAttachmentDtoEntityType
>;

export const CreateAttachmentDtoEntityType$zodSchema = z.enum([
  "task",
  "vendor",
  "risk",
  "comment",
  "trust_nda",
  "task_item",
  "background_check",
  "employment_onboard",
  "employment_offboard",
  "offboarding_checklist",
]).describe("Type of entity the attachment belongs to");

export type CreateAttachmentDto = {
  fileName: string;
  fileType: string;
  fileData: string;
  description?: string | undefined;
  userId?: string | undefined;
  entityId: string;
  entityType: CreateAttachmentDtoEntityType;
};

export const CreateAttachmentDto$zodSchema: z.ZodType<CreateAttachmentDto> = z
  .object({
    description: z.string().optional().describe(
      "Description of the attachment",
    ),
    entityId: z.string().describe("ID of the entity to attach the file to"),
    entityType: CreateAttachmentDtoEntityType$zodSchema.describe(
      "Type of entity the attachment belongs to",
    ),
    fileData: z.string().describe("Base64 encoded file data"),
    fileName: z.string().describe("Name of the file"),
    fileType: z.string().describe("MIME type of the file"),
    userId: z.string().optional().describe(
      "User ID of the user uploading the attachment (required for API key auth, ignored for JWT auth)",
    ),
  });
