/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Status of the policy
 */
export const CreatePolicyDtoStatus = {
  Draft: "draft",
  Published: "published",
  NeedsReview: "needs_review",
} as const;
/**
 * Status of the policy
 */
export type CreatePolicyDtoStatus = ClosedEnum<typeof CreatePolicyDtoStatus>;

export const CreatePolicyDtoStatus$zodSchema = z.enum([
  "draft",
  "published",
  "needs_review",
]).describe("Status of the policy");

/**
 * Review frequency of the policy
 */
export const CreatePolicyDtoFrequency = {
  Monthly: "monthly",
  Quarterly: "quarterly",
  Yearly: "yearly",
} as const;
/**
 * Review frequency of the policy
 */
export type CreatePolicyDtoFrequency = ClosedEnum<
  typeof CreatePolicyDtoFrequency
>;

export const CreatePolicyDtoFrequency$zodSchema = z.enum([
  "monthly",
  "quarterly",
  "yearly",
]).describe("Review frequency of the policy");

export type CreatePolicyDto = {
  name: string;
  description?: string | undefined;
  status?: CreatePolicyDtoStatus | undefined;
  content: Array<{ [k: string]: any }>;
  frequency?: CreatePolicyDtoFrequency | undefined;
  department?: string | undefined;
  isRequiredToSign?: boolean | undefined;
  reviewDate?: string | undefined;
  assigneeId?: string | undefined;
  approverId?: string | undefined;
  policyTemplateId?: string | undefined;
  signedBy?: Array<string> | undefined;
};

export const CreatePolicyDto$zodSchema: z.ZodType<CreatePolicyDto> = z.object({
  approverId: z.string().optional().describe(
    "ID of the user who approved this policy",
  ),
  assigneeId: z.string().optional().describe(
    "ID of the user assigned to this policy",
  ),
  content: z.array(z.record(z.string(), z.any())).describe(
    "Content of the policy as TipTap JSON (array of nodes)",
  ),
  department: z.string().optional().describe(
    "Department this policy applies to. Built-in values: none, admin, gov, hr, it, itsm, qms. Custom department names are also accepted.",
  ),
  description: z.string().optional().describe("Description of the policy"),
  frequency: CreatePolicyDtoFrequency$zodSchema.optional().describe(
    "Review frequency of the policy",
  ),
  isRequiredToSign: z.boolean().optional().describe(
    "Whether this policy requires a signature",
  ),
  name: z.string().describe("Name of the policy"),
  policyTemplateId: z.string().optional().describe(
    "ID of the policy template this policy is based on",
  ),
  reviewDate: z.string().optional().describe("Review date for the policy"),
  signedBy: z.array(z.string()).optional().describe(
    "List of user IDs who have signed this policy",
  ),
  status: CreatePolicyDtoStatus$zodSchema.optional().describe(
    "Status of the policy",
  ),
});
