/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateObjectiveDto = {};

export const CreateObjectiveDto$zodSchema: z.ZodType<CreateObjectiveDto> = z
  .object({});
