/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateCustomFrameworkDto = {
  name: string;
  description: string;
  version?: string | undefined;
};

export const CreateCustomFrameworkDto$zodSchema: z.ZodType<
  CreateCustomFrameworkDto
> = z.object({
  description: z.string().describe("Framework description"),
  name: z.string().describe("Framework name"),
  version: z.string().optional().describe("Version"),
});
