/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Vendor category
 */
export const CreateVendorDtoCategory = {
  Cloud: "cloud",
  Infrastructure: "infrastructure",
  SoftwareAsAService: "software_as_a_service",
  Finance: "finance",
  Marketing: "marketing",
  Sales: "sales",
  Hr: "hr",
  Other: "other",
} as const;
/**
 * Vendor category
 */
export type CreateVendorDtoCategory = ClosedEnum<
  typeof CreateVendorDtoCategory
>;

export const CreateVendorDtoCategory$zodSchema = z.enum([
  "cloud",
  "infrastructure",
  "software_as_a_service",
  "finance",
  "marketing",
  "sales",
  "hr",
  "other",
]).describe("Vendor category");

/**
 * Assessment status of the vendor
 */
export const CreateVendorDtoStatus = {
  NotAssessed: "not_assessed",
  InProgress: "in_progress",
  Assessed: "assessed",
} as const;
/**
 * Assessment status of the vendor
 */
export type CreateVendorDtoStatus = ClosedEnum<typeof CreateVendorDtoStatus>;

export const CreateVendorDtoStatus$zodSchema = z.enum([
  "not_assessed",
  "in_progress",
  "assessed",
]).describe("Assessment status of the vendor");

/**
 * Inherent probability of risk before controls
 */
export const CreateVendorDtoInherentProbability = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
/**
 * Inherent probability of risk before controls
 */
export type CreateVendorDtoInherentProbability = ClosedEnum<
  typeof CreateVendorDtoInherentProbability
>;

export const CreateVendorDtoInherentProbability$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]).describe("Inherent probability of risk before controls");

/**
 * Inherent impact of risk before controls
 */
export const CreateVendorDtoInherentImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Inherent impact of risk before controls
 */
export type CreateVendorDtoInherentImpact = ClosedEnum<
  typeof CreateVendorDtoInherentImpact
>;

export const CreateVendorDtoInherentImpact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]).describe("Inherent impact of risk before controls");

/**
 * Residual probability after controls are applied
 */
export const CreateVendorDtoResidualProbability = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
/**
 * Residual probability after controls are applied
 */
export type CreateVendorDtoResidualProbability = ClosedEnum<
  typeof CreateVendorDtoResidualProbability
>;

export const CreateVendorDtoResidualProbability$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]).describe("Residual probability after controls are applied");

/**
 * Residual impact after controls are applied
 */
export const CreateVendorDtoResidualImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Residual impact after controls are applied
 */
export type CreateVendorDtoResidualImpact = ClosedEnum<
  typeof CreateVendorDtoResidualImpact
>;

export const CreateVendorDtoResidualImpact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]).describe("Residual impact after controls are applied");

export type CreateVendorDto = {
  name: string;
  description: string;
  category?: CreateVendorDtoCategory | undefined;
  status?: CreateVendorDtoStatus | undefined;
  inherentProbability?: CreateVendorDtoInherentProbability | undefined;
  inherentImpact?: CreateVendorDtoInherentImpact | undefined;
  residualProbability?: CreateVendorDtoResidualProbability | undefined;
  residualImpact?: CreateVendorDtoResidualImpact | undefined;
  website?: string | undefined;
  isSubProcessor?: boolean | undefined;
  assigneeId?: string | undefined;
};

export const CreateVendorDto$zodSchema: z.ZodType<CreateVendorDto> = z.object({
  assigneeId: z.string().optional().describe(
    "ID of the user assigned to manage this vendor",
  ),
  category: CreateVendorDtoCategory$zodSchema.default("other").describe(
    "Vendor category",
  ),
  description: z.string().describe(
    "Detailed description of the vendor and services provided",
  ),
  inherentImpact: CreateVendorDtoInherentImpact$zodSchema.default(
    "insignificant",
  ).describe("Inherent impact of risk before controls"),
  inherentProbability: CreateVendorDtoInherentProbability$zodSchema.default(
    "very_unlikely",
  ).describe("Inherent probability of risk before controls"),
  isSubProcessor: z.boolean().default(false).describe(
    "Whether the vendor is a sub-processor",
  ),
  name: z.string().describe("Vendor name"),
  residualImpact: CreateVendorDtoResidualImpact$zodSchema.default(
    "insignificant",
  ).describe("Residual impact after controls are applied"),
  residualProbability: CreateVendorDtoResidualProbability$zodSchema.default(
    "very_unlikely",
  ).describe("Residual probability after controls are applied"),
  status: CreateVendorDtoStatus$zodSchema.default("not_assessed").describe(
    "Assessment status of the vendor",
  ),
  website: z.string().optional().describe("Vendor website URL"),
});
