/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  RequirementMappingDto,
  RequirementMappingDto$zodSchema,
} from "./requirementmappingdto.js";

export const DocumentType = {
  BoardMeeting: "board_meeting",
  ItLeadershipMeeting: "it_leadership_meeting",
  RiskCommitteeMeeting: "risk_committee_meeting",
  Meeting: "meeting",
  AccessRequest: "access_request",
  WhistleblowerReport: "whistleblower_report",
  PenetrationTest: "penetration_test",
  RbacMatrix: "rbac_matrix",
  InfrastructureInventory: "infrastructure_inventory",
  EmployeePerformanceEvaluation: "employee_performance_evaluation",
  NetworkDiagram: "network_diagram",
  TabletopExercise: "tabletop_exercise",
} as const;
export type DocumentType = ClosedEnum<typeof DocumentType>;

export const DocumentType$zodSchema = z.enum([
  "board_meeting",
  "it_leadership_meeting",
  "risk_committee_meeting",
  "meeting",
  "access_request",
  "whistleblower_report",
  "penetration_test",
  "rbac_matrix",
  "infrastructure_inventory",
  "employee_performance_evaluation",
  "network_diagram",
  "tabletop_exercise",
]);

export type CreateControlDto = {
  name: string;
  description: string;
  policyIds?: Array<string> | undefined;
  taskIds?: Array<string> | undefined;
  requirementMappings?: Array<RequirementMappingDto> | undefined;
  documentTypes?: Array<DocumentType> | undefined;
};

export const CreateControlDto$zodSchema: z.ZodType<CreateControlDto> = z.object(
  {
    description: z.string().describe("Control description"),
    documentTypes: z.array(DocumentType$zodSchema).optional().describe(
      "Evidence form types to require on this control",
    ),
    name: z.string().describe("Control name"),
    policyIds: z.array(z.string()).optional().describe("Policy IDs to connect"),
    requirementMappings: z.array(RequirementMappingDto$zodSchema).optional()
      .describe("Requirement mappings"),
    taskIds: z.array(z.string()).optional().describe("Task IDs to connect"),
  },
);
