/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DenyAccessRequestDto = { reason: string };

export const DenyAccessRequestDto$zodSchema: z.ZodType<DenyAccessRequestDto> = z
  .object({
    reason: z.string(),
  });
