/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  DeviceResponseDto,
  DeviceResponseDto$zodSchema,
} from "./deviceresponsedto.js";
import {
  MemberResponseDto,
  MemberResponseDto$zodSchema,
} from "./memberresponsedto.js";

/**
 * How the request was authenticated
 */
export const AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type AuthType = ClosedEnum<typeof AuthType>;

export const AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

/**
 * Authenticated user information (present for session auth)
 */
export type AuthenticatedUser = {};

export const AuthenticatedUser$zodSchema: z.ZodType<AuthenticatedUser> = z
  .object({}).describe(
    "Authenticated user information (present for session auth)",
  );

export type DevicesByMemberResponseDto = {
  data: Array<DeviceResponseDto>;
  count: number;
  member: MemberResponseDto;
  authType: AuthType;
  authenticatedUser?: AuthenticatedUser | undefined;
};

export const DevicesByMemberResponseDto$zodSchema: z.ZodType<
  DevicesByMemberResponseDto
> = z.object({
  authType: AuthType$zodSchema.describe("How the request was authenticated"),
  authenticatedUser: z.lazy(() => AuthenticatedUser$zodSchema).optional()
    .describe("Authenticated user information (present for session auth)"),
  count: z.number().describe("Total number of devices for this member"),
  data: z.array(DeviceResponseDto$zodSchema).describe(
    "Array of devices assigned to the member",
  ),
  member: MemberResponseDto$zodSchema.describe("Member information"),
});
