/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeviceAgentControllerRevokeAgentAccessV1Request = {
  deviceId: string;
};

export const DeviceAgentControllerRevokeAgentAccessV1Request$zodSchema:
  z.ZodType<DeviceAgentControllerRevokeAgentAccessV1Request> = z.object({
    deviceId: z.string(),
  });
