/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EmailPreferencesDto = {
  policyNotifications: boolean;
  taskReminders: boolean;
  weeklyTaskDigest: boolean;
  unassignedItemsNotifications: boolean;
  taskMentions: boolean;
  taskAssignments: boolean;
};

export const EmailPreferencesDto$zodSchema: z.ZodType<EmailPreferencesDto> = z
  .object({
    policyNotifications: z.boolean(),
    taskAssignments: z.boolean(),
    taskMentions: z.boolean(),
    taskReminders: z.boolean(),
    unassignedItemsNotifications: z.boolean(),
    weeklyTaskDigest: z.boolean(),
  });
