/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EnsureIsmsSetupDto = { frameworkId: string };

export const EnsureIsmsSetupDto$zodSchema: z.ZodType<EnsureIsmsSetupDto> = z
  .object({
    frameworkId: z.string().describe(
      "ID of the framework to scope the ISMS setup to",
    ),
  });
