/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EvidenceExportControllerExportAutomationPdfv1Request = {
  taskId: string;
  automationId: string;
};

export const EvidenceExportControllerExportAutomationPdfv1Request$zodSchema:
  z.ZodType<EvidenceExportControllerExportAutomationPdfv1Request> = z.object({
    automationId: z.string().describe(
      "Unique automation identifier (checkId for app automations)",
    ),
    taskId: z.string().describe("Unique task identifier"),
  });
