/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ExportIsmsDocumentDto = {};

export const ExportIsmsDocumentDto$zodSchema: z.ZodType<ExportIsmsDocumentDto> =
  z.object({});
