/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateFindingDto,
  UpdateFindingDto$zodSchema,
} from "./updatefindingdto.js";

export type FindingsControllerUpdateFindingV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const FindingsControllerUpdateFindingV1Security$zodSchema: z.ZodType<
  FindingsControllerUpdateFindingV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type FindingsControllerUpdateFindingV1Request = {
  id: string;
  body: UpdateFindingDto;
};

export const FindingsControllerUpdateFindingV1Request$zodSchema: z.ZodType<
  FindingsControllerUpdateFindingV1Request
> = z.object({
  body: UpdateFindingDto$zodSchema,
  id: z.string().describe("Finding ID"),
});
