/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FindingsControllerGetFindingByIdV1Request = { id: string };

export const FindingsControllerGetFindingByIdV1Request$zodSchema: z.ZodType<
  FindingsControllerGetFindingByIdV1Request
> = z.object({
  id: z.string().describe("Finding ID"),
});
