/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FindingsControllerGetOrganizationFindingsV1Status = {
  Open: "open",
  ReadyForReview: "ready_for_review",
  NeedsRevision: "needs_revision",
  Closed: "closed",
} as const;
export type FindingsControllerGetOrganizationFindingsV1Status = ClosedEnum<
  typeof FindingsControllerGetOrganizationFindingsV1Status
>;

export const FindingsControllerGetOrganizationFindingsV1Status$zodSchema = z
  .enum([
    "open",
    "ready_for_review",
    "needs_revision",
    "closed",
  ]);

export type FindingsControllerGetOrganizationFindingsV1Request = {
  status?: FindingsControllerGetOrganizationFindingsV1Status | undefined;
};

export const FindingsControllerGetOrganizationFindingsV1Request$zodSchema:
  z.ZodType<FindingsControllerGetOrganizationFindingsV1Request> = z.object({
    status: FindingsControllerGetOrganizationFindingsV1Status$zodSchema
      .optional(),
  });
