/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Team ID
 */
export type FleetPolicyDtoTeamId = {};

export const FleetPolicyDtoTeamId$zodSchema: z.ZodType<FleetPolicyDtoTeamId> = z
  .object({}).describe("Team ID");

export type FleetPolicyDto = {
  id: number;
  name: string;
  query: string;
  critical: boolean;
  description: string;
  author_id: number;
  author_name: string;
  author_email: string;
  team_id: FleetPolicyDtoTeamId | null;
  resolution: string;
  platform: string;
  calendar_events_enabled: boolean;
  created_at: string;
  updated_at: string;
  response: string;
};

export const FleetPolicyDto$zodSchema: z.ZodType<FleetPolicyDto> = z.object({
  author_email: z.string().describe("Author email"),
  author_id: z.number().describe("Author ID"),
  author_name: z.string().describe("Author name"),
  calendar_events_enabled: z.boolean().describe("Calendar events enabled"),
  created_at: z.string().describe("Created at"),
  critical: z.boolean().describe("Whether policy is critical"),
  description: z.string().describe("Policy description"),
  id: z.number().describe("Policy ID"),
  name: z.string().describe("Policy name"),
  platform: z.string().describe("Platform"),
  query: z.string().describe("Policy query"),
  resolution: z.string().describe("Policy resolution"),
  response: z.string().describe("Policy response"),
  team_id: z.lazy(() => FleetPolicyDtoTeamId$zodSchema).nullable().describe(
    "Team ID",
  ),
  updated_at: z.string().describe("Updated at"),
});
