/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LinkControlsDto,
  LinkControlsDto$zodSchema,
} from "./linkcontrolsdto.js";

export type FrameworksControllerLinkControlsV1Security = { bearer: string };

export const FrameworksControllerLinkControlsV1Security$zodSchema: z.ZodType<
  FrameworksControllerLinkControlsV1Security
> = z.object({
  bearer: z.string().describe("API Key"),
});

export type FrameworksControllerLinkControlsV1Request = {
  id: string;
  requirementKey: string;
  body: LinkControlsDto;
};

export const FrameworksControllerLinkControlsV1Request$zodSchema: z.ZodType<
  FrameworksControllerLinkControlsV1Request
> = z.object({
  body: LinkControlsDto$zodSchema,
  id: z.string(),
  requirementKey: z.string(),
});
