/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateCustomFrameworkDto,
  UpdateCustomFrameworkDto$zodSchema,
} from "./updatecustomframeworkdto.js";

export type FrameworksControllerUpdateCustomV1Security = { bearer: string };

export const FrameworksControllerUpdateCustomV1Security$zodSchema: z.ZodType<
  FrameworksControllerUpdateCustomV1Security
> = z.object({
  bearer: z.string().describe("API Key"),
});

export type FrameworksControllerUpdateCustomV1Request = {
  id: string;
  body: UpdateCustomFrameworkDto;
};

export const FrameworksControllerUpdateCustomV1Request$zodSchema: z.ZodType<
  FrameworksControllerUpdateCustomV1Request
> = z.object({
  body: UpdateCustomFrameworkDto$zodSchema,
  id: z.string(),
});
