/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ExportIsmsDocumentDto,
  ExportIsmsDocumentDto$zodSchema,
} from "./exportismsdocumentdto.js";

export type IsmsControllerExportDocumentV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsControllerExportDocumentV1Security$zodSchema: z.ZodType<
  IsmsControllerExportDocumentV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsControllerExportDocumentV1Request = {
  id: string;
  body: ExportIsmsDocumentDto;
};

export const IsmsControllerExportDocumentV1Request$zodSchema: z.ZodType<
  IsmsControllerExportDocumentV1Request
> = z.object({
  body: ExportIsmsDocumentDto$zodSchema,
  id: z.string(),
});
