/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LinkIsmsControlsDto,
  LinkIsmsControlsDto$zodSchema,
} from "./linkismscontrolsdto.js";

export type IsmsControllerAddControlsV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsControllerAddControlsV1Security$zodSchema: z.ZodType<
  IsmsControllerAddControlsV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsControllerAddControlsV1Request = {
  id: string;
  body: LinkIsmsControlsDto;
};

export const IsmsControllerAddControlsV1Request$zodSchema: z.ZodType<
  IsmsControllerAddControlsV1Request
> = z.object({
  body: LinkIsmsControlsDto$zodSchema,
  id: z.string(),
});
