/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateContextIssueDto,
  UpdateContextIssueDto$zodSchema,
} from "./updatecontextissuedto.js";

export type IsmsControllerUpdateContextIssueV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsControllerUpdateContextIssueV1Security$zodSchema: z.ZodType<
  IsmsControllerUpdateContextIssueV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsControllerUpdateContextIssueV1Request = {
  issueId: string;
  body: UpdateContextIssueDto;
};

export const IsmsControllerUpdateContextIssueV1Request$zodSchema: z.ZodType<
  IsmsControllerUpdateContextIssueV1Request
> = z.object({
  body: UpdateContextIssueDto$zodSchema,
  issueId: z.string(),
});
