/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsControllerDeleteContextIssueV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsControllerDeleteContextIssueV1Security$zodSchema: z.ZodType<
  IsmsControllerDeleteContextIssueV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsControllerDeleteContextIssueV1Request = { issueId: string };

export const IsmsControllerDeleteContextIssueV1Request$zodSchema: z.ZodType<
  IsmsControllerDeleteContextIssueV1Request
> = z.object({
  issueId: z.string(),
});
