/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const IsmsRegistersControllerCreateRowV1Kind = {
  Internal: "internal",
  External: "external",
} as const;
export type IsmsRegistersControllerCreateRowV1Kind = ClosedEnum<
  typeof IsmsRegistersControllerCreateRowV1Kind
>;

export const IsmsRegistersControllerCreateRowV1Kind$zodSchema = z.enum([
  "internal",
  "external",
]);

export const IsmsRegistersControllerCreateRowV1Status = {
  NotStarted: "not_started",
  OnTrack: "on_track",
  AtRisk: "at_risk",
  Met: "met",
} as const;
export type IsmsRegistersControllerCreateRowV1Status = ClosedEnum<
  typeof IsmsRegistersControllerCreateRowV1Status
>;

export const IsmsRegistersControllerCreateRowV1Status$zodSchema = z.enum([
  "not_started",
  "on_track",
  "at_risk",
  "met",
]);

/**
 * Register row fields (per-register; validated at runtime by zod)
 */
export type IsmsRegistersControllerCreateRowV1RequestBody = {
  kind?: IsmsRegistersControllerCreateRowV1Kind | undefined;
  category?: string | undefined;
  description?: string | undefined;
  effect?: string | undefined;
  name?: string | undefined;
  needsExpectations?: string | undefined;
  interestedPartyId?: string | undefined;
  partyName?: string | undefined;
  requirement?: string | undefined;
  treatment?: string | undefined;
  objective?: string | undefined;
  target?: string | undefined;
  ownerMemberId?: string | undefined;
  cadence?: string | undefined;
  plan?: string | undefined;
  measurementMethod?: string | undefined;
  status?: IsmsRegistersControllerCreateRowV1Status | undefined;
  position?: number | undefined;
};

export const IsmsRegistersControllerCreateRowV1RequestBody$zodSchema: z.ZodType<
  IsmsRegistersControllerCreateRowV1RequestBody
> = z.object({
  cadence: z.string().optional(),
  category: z.string().optional(),
  description: z.string().optional(),
  effect: z.string().optional(),
  interestedPartyId: z.string().optional(),
  kind: IsmsRegistersControllerCreateRowV1Kind$zodSchema.optional(),
  measurementMethod: z.string().optional(),
  name: z.string().optional(),
  needsExpectations: z.string().optional(),
  objective: z.string().optional(),
  ownerMemberId: z.string().optional(),
  partyName: z.string().optional(),
  plan: z.string().optional(),
  position: z.int().optional(),
  requirement: z.string().optional(),
  status: IsmsRegistersControllerCreateRowV1Status$zodSchema.optional(),
  target: z.string().optional(),
  treatment: z.string().optional(),
}).describe("Register row fields (per-register; validated at runtime by zod)");

export type IsmsRegistersControllerCreateRowV1Request = {
  id: string;
  register: string;
  body: IsmsRegistersControllerCreateRowV1RequestBody;
};

export const IsmsRegistersControllerCreateRowV1Request$zodSchema: z.ZodType<
  IsmsRegistersControllerCreateRowV1Request
> = z.object({
  body: z.lazy(() => IsmsRegistersControllerCreateRowV1RequestBody$zodSchema)
    .describe(
      "Register row fields (per-register; validated at runtime by zod)",
    ),
  id: z.string(),
  register: z.string(),
});
