/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsControllerRemoveControlV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsControllerRemoveControlV1Security$zodSchema: z.ZodType<
  IsmsControllerRemoveControlV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsControllerRemoveControlV1Request = {
  id: string;
  controlId: string;
};

export const IsmsControllerRemoveControlV1Request$zodSchema: z.ZodType<
  IsmsControllerRemoveControlV1Request
> = z.object({
  controlId: z.string(),
  id: z.string(),
});
