/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsRegistersControllerDeleteObjectiveV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsRegistersControllerDeleteObjectiveV1Security$zodSchema:
  z.ZodType<IsmsRegistersControllerDeleteObjectiveV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe("API Key").optional(),
  });

export type IsmsRegistersControllerDeleteObjectiveV1Request = {
  objectiveId: string;
};

export const IsmsRegistersControllerDeleteObjectiveV1Request$zodSchema:
  z.ZodType<IsmsRegistersControllerDeleteObjectiveV1Request> = z.object({
    objectiveId: z.string(),
  });
