/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateObjectiveDto,
  CreateObjectiveDto$zodSchema,
} from "./createobjectivedto.js";

export type IsmsRegistersControllerCreateObjectiveV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsRegistersControllerCreateObjectiveV1Security$zodSchema:
  z.ZodType<IsmsRegistersControllerCreateObjectiveV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe("API Key").optional(),
  });

export type IsmsRegistersControllerCreateObjectiveV1Request = {
  id: string;
  body: CreateObjectiveDto;
};

export const IsmsRegistersControllerCreateObjectiveV1Request$zodSchema:
  z.ZodType<IsmsRegistersControllerCreateObjectiveV1Request> = z.object({
    body: CreateObjectiveDto$zodSchema,
    id: z.string(),
  });
