/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsControllerGenerateV1Request = { id: string };

export const IsmsControllerGenerateV1Request$zodSchema: z.ZodType<
  IsmsControllerGenerateV1Request
> = z.object({
  id: z.string(),
});
