/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Singleton document narrative payload
 */
export type IsmsRegistersControllerSaveNarrativeV1RequestBody = {
  narrative: { [k: string]: any };
};

export const IsmsRegistersControllerSaveNarrativeV1RequestBody$zodSchema:
  z.ZodType<IsmsRegistersControllerSaveNarrativeV1RequestBody> = z.object({
    narrative: z.record(z.string(), z.any()).describe(
      "Per-type narrative object (e.g. ISMS scope or leadership commitment), validated at runtime by zod",
    ),
  }).describe("Singleton document narrative payload");

export type IsmsRegistersControllerSaveNarrativeV1Request = {
  id: string;
  body: IsmsRegistersControllerSaveNarrativeV1RequestBody;
};

export const IsmsRegistersControllerSaveNarrativeV1Request$zodSchema: z.ZodType<
  IsmsRegistersControllerSaveNarrativeV1Request
> = z.object({
  body: z.lazy(() =>
    IsmsRegistersControllerSaveNarrativeV1RequestBody$zodSchema
  ).describe("Singleton document narrative payload"),
  id: z.string(),
});
