/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsProfileControllerGetProfileV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsProfileControllerGetProfileV1Security$zodSchema: z.ZodType<
  IsmsProfileControllerGetProfileV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe("API Key").optional(),
});

export type IsmsProfileControllerGetProfileV1Request = { frameworkId: string };

export const IsmsProfileControllerGetProfileV1Request$zodSchema: z.ZodType<
  IsmsProfileControllerGetProfileV1Request
> = z.object({
  frameworkId: z.string(),
});
