/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsRegistersControllerDeleteRowV1Request = {
  register: string;
  rowId: string;
};

export const IsmsRegistersControllerDeleteRowV1Request$zodSchema: z.ZodType<
  IsmsRegistersControllerDeleteRowV1Request
> = z.object({
  register: z.string(),
  rowId: z.string(),
});
