/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IsmsProfileControllerGetProfileV1Request = { frameworkId: string };

export const IsmsProfileControllerGetProfileV1Request$zodSchema: z.ZodType<
  IsmsProfileControllerGetProfileV1Request
> = z.object({
  frameworkId: z.string(),
});
