/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateRequirementDto,
  CreateRequirementDto$zodSchema,
} from "./createrequirementdto.js";

export type IsmsRegistersControllerCreateRequirementV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsRegistersControllerCreateRequirementV1Security$zodSchema:
  z.ZodType<IsmsRegistersControllerCreateRequirementV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe("API Key").optional(),
  });

export type IsmsRegistersControllerCreateRequirementV1Request = {
  id: string;
  body: CreateRequirementDto;
};

export const IsmsRegistersControllerCreateRequirementV1Request$zodSchema:
  z.ZodType<IsmsRegistersControllerCreateRequirementV1Request> = z.object({
    body: CreateRequirementDto$zodSchema,
    id: z.string(),
  });
