/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateInterestedPartyDto,
  UpdateInterestedPartyDto$zodSchema,
} from "./updateinterestedpartydto.js";

export type IsmsRegistersControllerUpdateInterestedPartyV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const IsmsRegistersControllerUpdateInterestedPartyV1Security$zodSchema:
  z.ZodType<IsmsRegistersControllerUpdateInterestedPartyV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe("API Key").optional(),
  });

export type IsmsRegistersControllerUpdateInterestedPartyV1Request = {
  partyId: string;
  body: UpdateInterestedPartyDto;
};

export const IsmsRegistersControllerUpdateInterestedPartyV1Request$zodSchema:
  z.ZodType<IsmsRegistersControllerUpdateInterestedPartyV1Request> = z.object({
    body: UpdateInterestedPartyDto$zodSchema,
    partyId: z.string(),
  });
