/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type KnowledgeBaseControllerDeleteDocumentV1Request = {
  documentId: string;
};

export const KnowledgeBaseControllerDeleteDocumentV1Request$zodSchema:
  z.ZodType<KnowledgeBaseControllerDeleteDocumentV1Request> = z.object({
    documentId: z.string(),
  });
