/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type KnowledgeBaseControllerGetViewUrlV1Request = { documentId: string };

export const KnowledgeBaseControllerGetViewUrlV1Request$zodSchema: z.ZodType<
  KnowledgeBaseControllerGetViewUrlV1Request
> = z.object({
  documentId: z.string(),
});
