/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeleteManualAnswerDto,
  DeleteManualAnswerDto$zodSchema,
} from "./deletemanualanswerdto.js";

export type KnowledgeBaseControllerDeleteManualAnswerV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const KnowledgeBaseControllerDeleteManualAnswerV1Security$zodSchema:
  z.ZodType<KnowledgeBaseControllerDeleteManualAnswerV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type KnowledgeBaseControllerDeleteManualAnswerV1Request = {
  manualAnswerId: string;
  body: DeleteManualAnswerDto;
};

export const KnowledgeBaseControllerDeleteManualAnswerV1Request$zodSchema:
  z.ZodType<KnowledgeBaseControllerDeleteManualAnswerV1Request> = z.object({
    body: DeleteManualAnswerDto$zodSchema,
    manualAnswerId: z.string(),
  });
