/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinkTasksDto = { taskIds: Array<string> };

export const LinkTasksDto$zodSchema: z.ZodType<LinkTasksDto> = z.object({
  taskIds: z.array(z.string()).describe("Task IDs to link to the control"),
});
