/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinkRequirementMappingDto = {
  requirementId?: string | undefined;
  customRequirementId?: string | undefined;
  frameworkInstanceId: string;
};

export const LinkRequirementMappingDto$zodSchema: z.ZodType<
  LinkRequirementMappingDto
> = z.object({
  customRequirementId: z.string().optional().describe(
    "Org-custom requirement ID",
  ),
  frameworkInstanceId: z.string().describe("Framework instance ID"),
  requirementId: z.string().optional().describe("Platform requirement ID"),
});
