/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinkPoliciesDto = { policyIds: Array<string> };

export const LinkPoliciesDto$zodSchema: z.ZodType<LinkPoliciesDto> = z.object({
  policyIds: z.array(z.string()).describe("Policy IDs to link to the control"),
});
