/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CompleteChecklistItemDto,
  CompleteChecklistItemDto$zodSchema,
} from "./completechecklistitemdto.js";

export type OffboardingChecklistControllerCompleteItemV1Request = {
  memberId: string;
  templateItemId: string;
  body: CompleteChecklistItemDto;
};

export const OffboardingChecklistControllerCompleteItemV1Request$zodSchema:
  z.ZodType<OffboardingChecklistControllerCompleteItemV1Request> = z.object({
    body: CompleteChecklistItemDto$zodSchema,
    memberId: z.string(),
    templateItemId: z.string(),
  });
