/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateTemplateItemDto,
  UpdateTemplateItemDto$zodSchema,
} from "./updatetemplateitemdto.js";

export type OffboardingChecklistControllerUpdateTemplateItemV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const OffboardingChecklistControllerUpdateTemplateItemV1Security$zodSchema:
  z.ZodType<OffboardingChecklistControllerUpdateTemplateItemV1Security> = z
    .object({
      apikey: z.string().describe("API key for authentication").optional(),
      oauth2: z.string().describe(
        "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
      ).optional(),
    });

export type OffboardingChecklistControllerUpdateTemplateItemV1Request = {
  id: string;
  body: UpdateTemplateItemDto;
};

export const OffboardingChecklistControllerUpdateTemplateItemV1Request$zodSchema:
  z.ZodType<OffboardingChecklistControllerUpdateTemplateItemV1Request> = z
    .object({
      body: UpdateTemplateItemDto$zodSchema,
      id: z.string(),
    });
