/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UploadAttachmentDto,
  UploadAttachmentDto$zodSchema,
} from "./uploadattachmentdto.js";

export type OffboardingChecklistControllerUploadEvidenceV1Request = {
  memberId: string;
  templateItemId: string;
  body: UploadAttachmentDto;
};

export const OffboardingChecklistControllerUploadEvidenceV1Request$zodSchema:
  z.ZodType<OffboardingChecklistControllerUploadEvidenceV1Request> = z.object({
    body: UploadAttachmentDto$zodSchema,
    memberId: z.string(),
    templateItemId: z.string(),
  });
