/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OffboardingChecklistControllerUndoVendorRevocationV1Request = {
  memberId: string;
  vendorId: string;
};

export const OffboardingChecklistControllerUndoVendorRevocationV1Request$zodSchema:
  z.ZodType<OffboardingChecklistControllerUndoVendorRevocationV1Request> = z
    .object({
      memberId: z.string().describe("Member ID"),
      vendorId: z.string().describe("Vendor ID"),
    });
