/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OffboardingChecklistControllerGetMemberChecklistV1Request = {
  memberId: string;
};

export const OffboardingChecklistControllerGetMemberChecklistV1Request$zodSchema:
  z.ZodType<OffboardingChecklistControllerGetMemberChecklistV1Request> = z
    .object({
      memberId: z.string(),
    });
