/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type OrganizationControllerGetPrimaryColorV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const OrganizationControllerGetPrimaryColorV1Security$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type OrganizationControllerGetPrimaryColorV1Request = {
  token?: any | undefined;
};

export const OrganizationControllerGetPrimaryColorV1Request$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1Request> = z.object({
    token: z.any().describe(
      "Access token for public access (alternative to authentication). When provided, authentication is not required.",
    ).optional(),
  });

/**
 * Organization not found
 */
export type OrganizationControllerGetPrimaryColorV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const OrganizationControllerGetPrimaryColorV1NotFoundResponseBody$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Organization not found");

/**
 * Unauthorized - Invalid authentication or insufficient permissions
 */
export type OrganizationControllerGetPrimaryColorV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const OrganizationControllerGetPrimaryColorV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe(
      "Unauthorized - Invalid authentication or insufficient permissions",
    );

/**
 * How the request was authenticated
 */
export const OrganizationControllerGetPrimaryColorV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type OrganizationControllerGetPrimaryColorV1AuthType = ClosedEnum<
  typeof OrganizationControllerGetPrimaryColorV1AuthType
>;

export const OrganizationControllerGetPrimaryColorV1AuthType$zodSchema = z.enum(
  [
    "api-key",
    "session",
  ],
).describe("How the request was authenticated");

/**
 * Organization primary color retrieved successfully
 */
export type OrganizationControllerGetPrimaryColorV1ResponseBody = {
  primaryColor?: string | null | undefined;
  authType?: OrganizationControllerGetPrimaryColorV1AuthType | undefined;
};

export const OrganizationControllerGetPrimaryColorV1ResponseBody$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1ResponseBody> = z.object({
    authType: OrganizationControllerGetPrimaryColorV1AuthType$zodSchema
      .optional().describe("How the request was authenticated"),
    primaryColor: z.string().nullable().optional().describe(
      "The primary color in hex format (e.g., #FF5733)",
    ),
  }).describe("Organization primary color retrieved successfully");

export type OrganizationControllerGetPrimaryColorV1Response =
  | OrganizationControllerGetPrimaryColorV1ResponseBody
  | OrganizationControllerGetPrimaryColorV1UnauthorizedResponseBody
  | OrganizationControllerGetPrimaryColorV1NotFoundResponseBody;

export const OrganizationControllerGetPrimaryColorV1Response$zodSchema:
  z.ZodType<OrganizationControllerGetPrimaryColorV1Response> = z.union([
    z.lazy(() => OrganizationControllerGetPrimaryColorV1ResponseBody$zodSchema),
    z.lazy(() =>
      OrganizationControllerGetPrimaryColorV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      OrganizationControllerGetPrimaryColorV1NotFoundResponseBody$zodSchema
    ),
  ]);
