/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * How the request was authenticated
 */
export const OrganizationControllerUpdateOrganizationV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type OrganizationControllerUpdateOrganizationV1AuthType = ClosedEnum<
  typeof OrganizationControllerUpdateOrganizationV1AuthType
>;

export const OrganizationControllerUpdateOrganizationV1AuthType$zodSchema = z
  .enum([
    "api-key",
    "session",
  ]).describe("How the request was authenticated");

/**
 * Organization update data
 */
export type OrganizationControllerUpdateOrganizationV1Request = {
  name?: string | undefined;
  slug?: string | undefined;
  logo?: string | undefined;
  metadata?: string | undefined;
  website?: string | undefined;
  onboardingCompleted?: boolean | undefined;
  fleetDmLabelId?: number | undefined;
  isFleetSetupCompleted?: boolean | undefined;
  primaryColor?: string | undefined;
  advancedModeEnabled?: boolean | undefined;
  backgroundCheckStepEnabled?: boolean | undefined;
  evidenceApprovalEnabled?: boolean | undefined;
  deviceAgentStepEnabled?: boolean | undefined;
  securityTrainingStepEnabled?: boolean | undefined;
  whistleblowerReportEnabled?: boolean | undefined;
  accessRequestFormEnabled?: boolean | undefined;
};

export const OrganizationControllerUpdateOrganizationV1Request$zodSchema:
  z.ZodType<OrganizationControllerUpdateOrganizationV1Request> = z.object({
    accessRequestFormEnabled: z.boolean().optional().describe(
      "Whether the trust-portal access request form is enabled.",
    ),
    advancedModeEnabled: z.boolean().optional().describe(
      "Whether advanced mode is enabled for the organization",
    ),
    backgroundCheckStepEnabled: z.boolean().optional().describe(
      "Whether the background-check step is required during member onboarding. Set to false to turn off the \"Require background checks\" setting; true to require it.",
    ),
    deviceAgentStepEnabled: z.boolean().optional().describe(
      "Whether the device-agent step is enabled during member onboarding.",
    ),
    evidenceApprovalEnabled: z.boolean().optional().describe(
      "Whether evidence requires approval before it is accepted.",
    ),
    fleetDmLabelId: z.int().optional().describe(
      "FleetDM label ID for device management",
    ),
    isFleetSetupCompleted: z.boolean().optional().describe(
      "Whether FleetDM setup is completed",
    ),
    logo: z.string().optional().describe("Organization logo URL"),
    metadata: z.string().optional().describe(
      "Additional metadata in JSON format",
    ),
    name: z.string().optional().describe("Organization name"),
    onboardingCompleted: z.boolean().optional().describe(
      "Whether onboarding is completed",
    ),
    primaryColor: z.string().optional().describe(
      "Organization primary color in hex format",
    ),
    securityTrainingStepEnabled: z.boolean().optional().describe(
      "Whether the security-training step is enabled during member onboarding.",
    ),
    slug: z.string().optional().describe("Organization slug"),
    website: z.string().optional().describe("Organization website URL"),
    whistleblowerReportEnabled: z.boolean().optional().describe(
      "Whether the whistleblower reporting feature is enabled.",
    ),
  }).describe("Organization update data");

/**
 * Organization not found
 */
export type OrganizationControllerUpdateOrganizationV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const OrganizationControllerUpdateOrganizationV1NotFoundResponseBody$zodSchema:
  z.ZodType<OrganizationControllerUpdateOrganizationV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Organization not found");

/**
 * Unauthorized - Invalid authentication or insufficient permissions
 */
export type OrganizationControllerUpdateOrganizationV1UnauthorizedResponseBody =
  { message?: string | undefined };

export const OrganizationControllerUpdateOrganizationV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<
    OrganizationControllerUpdateOrganizationV1UnauthorizedResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe(
    "Unauthorized - Invalid authentication or insufficient permissions",
  );

/**
 * Bad Request - Invalid update data
 */
export type OrganizationControllerUpdateOrganizationV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const OrganizationControllerUpdateOrganizationV1BadRequestResponseBody$zodSchema:
  z.ZodType<OrganizationControllerUpdateOrganizationV1BadRequestResponseBody> =
    z.object({
      message: z.string().optional(),
    }).describe("Bad Request - Invalid update data");

/**
 * Organization updated successfully
 */
export type OrganizationControllerUpdateOrganizationV1ResponseBody = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  logo?: string | null | undefined;
  metadata?: string | null | undefined;
  website?: string | null | undefined;
  onboardingCompleted?: boolean | undefined;
  hasAccess?: boolean | undefined;
  fleetDmLabelId?: number | null | undefined;
  isFleetSetupCompleted?: boolean | undefined;
  primaryColor?: string | null | undefined;
  createdAt?: string | undefined;
  authType?: OrganizationControllerUpdateOrganizationV1AuthType | undefined;
};

export const OrganizationControllerUpdateOrganizationV1ResponseBody$zodSchema:
  z.ZodType<OrganizationControllerUpdateOrganizationV1ResponseBody> = z.object({
    authType: OrganizationControllerUpdateOrganizationV1AuthType$zodSchema
      .optional().describe("How the request was authenticated"),
    createdAt: z.iso.datetime({ offset: true }).optional().describe(
      "When the organization was created",
    ),
    fleetDmLabelId: z.int().nullable().optional().describe(
      "FleetDM label ID for device management",
    ),
    hasAccess: z.boolean().optional().describe(
      "Whether organization has access to the platform",
    ),
    id: z.string().optional().describe("The organization ID"),
    isFleetSetupCompleted: z.boolean().optional().describe(
      "Whether FleetDM setup is completed",
    ),
    logo: z.string().nullable().optional().describe("Organization logo URL"),
    metadata: z.string().nullable().optional().describe(
      "Additional metadata in JSON format",
    ),
    name: z.string().optional().describe("Organization name"),
    onboardingCompleted: z.boolean().optional().describe(
      "Whether onboarding is completed",
    ),
    primaryColor: z.string().nullable().optional().describe(
      "Organization primary color in hex format",
    ),
    slug: z.string().optional().describe("Organization slug"),
    website: z.string().nullable().optional().describe(
      "Organization website URL",
    ),
  }).describe("Organization updated successfully");

export type OrganizationControllerUpdateOrganizationV1Response =
  | OrganizationControllerUpdateOrganizationV1ResponseBody
  | OrganizationControllerUpdateOrganizationV1BadRequestResponseBody
  | OrganizationControllerUpdateOrganizationV1UnauthorizedResponseBody
  | OrganizationControllerUpdateOrganizationV1NotFoundResponseBody;

export const OrganizationControllerUpdateOrganizationV1Response$zodSchema:
  z.ZodType<OrganizationControllerUpdateOrganizationV1Response> = z.union([
    z.lazy(() =>
      OrganizationControllerUpdateOrganizationV1ResponseBody$zodSchema
    ),
    z.lazy(() =>
      OrganizationControllerUpdateOrganizationV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      OrganizationControllerUpdateOrganizationV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      OrganizationControllerUpdateOrganizationV1NotFoundResponseBody$zodSchema
    ),
  ]);
