/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UploadOrgChartDto,
  UploadOrgChartDto$zodSchema,
} from "./uploadorgchartdto.js";

export type OrgChartControllerUploadOrgChartV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const OrgChartControllerUploadOrgChartV1Security$zodSchema: z.ZodType<
  OrgChartControllerUploadOrgChartV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type OrgChartControllerUploadOrgChartV1Request = {
  xOrganizationId?: string | undefined;
  body: UploadOrgChartDto;
};

export const OrgChartControllerUploadOrgChartV1Request$zodSchema: z.ZodType<
  OrgChartControllerUploadOrgChartV1Request
> = z.object({
  body: UploadOrgChartDto$zodSchema,
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});
