/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UploadOrgChartDto,
  UploadOrgChartDto$zodSchema,
} from "./uploadorgchartdto.js";

export type OrgChartControllerUploadOrgChartV1Request = {
  xOrganizationId?: string | undefined;
  body: UploadOrgChartDto;
};

export const OrgChartControllerUploadOrgChartV1Request$zodSchema: z.ZodType<
  OrgChartControllerUploadOrgChartV1Request
> = z.object({
  body: UploadOrgChartDto$zodSchema,
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});
