/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PeopleControllerReactivateMemberV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PeopleControllerReactivateMemberV1Security$zodSchema: z.ZodType<
  PeopleControllerReactivateMemberV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type PeopleControllerReactivateMemberV1Request = { id: string };

export const PeopleControllerReactivateMemberV1Request$zodSchema: z.ZodType<
  PeopleControllerReactivateMemberV1Request
> = z.object({
  id: z.string().describe("Member ID"),
});
