/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type PeopleControllerDeleteEmploymentEvidenceV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PeopleControllerDeleteEmploymentEvidenceV1Security$zodSchema:
  z.ZodType<PeopleControllerDeleteEmploymentEvidenceV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export const PeopleControllerDeleteEmploymentEvidenceV1EventType = {
  Onboard: "onboard",
  Offboard: "offboard",
} as const;
export type PeopleControllerDeleteEmploymentEvidenceV1EventType = ClosedEnum<
  typeof PeopleControllerDeleteEmploymentEvidenceV1EventType
>;

export const PeopleControllerDeleteEmploymentEvidenceV1EventType$zodSchema = z
  .enum([
    "onboard",
    "offboard",
  ]);

export type PeopleControllerDeleteEmploymentEvidenceV1Request = {
  id: string;
  eventType: PeopleControllerDeleteEmploymentEvidenceV1EventType;
  attachmentId: string;
};

export const PeopleControllerDeleteEmploymentEvidenceV1Request$zodSchema:
  z.ZodType<PeopleControllerDeleteEmploymentEvidenceV1Request> = z.object({
    attachmentId: z.string().describe("Attachment ID"),
    eventType: PeopleControllerDeleteEmploymentEvidenceV1EventType$zodSchema,
    id: z.string().describe("Member ID"),
  });
