/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BackgroundCheckSummaryDto,
  BackgroundCheckSummaryDto$zodSchema,
} from "./backgroundchecksummarydto.js";
import {
  UserResponseDto,
  UserResponseDto$zodSchema,
} from "./userresponsedto.js";

/**
 * Job title for the member
 */
export type JobTitle = {};

export const JobTitle$zodSchema: z.ZodType<JobTitle> = z.object({}).describe(
  "Job title for the member",
);

/**
 * FleetDM label ID for member devices
 */
export type PeopleResponseDtoFleetDmLabelId = {};

export const PeopleResponseDtoFleetDmLabelId$zodSchema: z.ZodType<
  PeopleResponseDtoFleetDmLabelId
> = z.object({}).describe("FleetDM label ID for member devices");

export type PeopleResponseDto = {
  id: string;
  organizationId: string;
  userId: string;
  role: string;
  createdAt: string;
  department: string;
  jobTitle: JobTitle | null;
  isActive: boolean;
  deactivated: boolean;
  fleetDmLabelId: PeopleResponseDtoFleetDmLabelId | null;
  user: UserResponseDto;
  backgroundCheckRequests?: Array<BackgroundCheckSummaryDto> | undefined;
};

export const PeopleResponseDto$zodSchema: z.ZodType<PeopleResponseDto> = z
  .object({
    backgroundCheckRequests: z.array(BackgroundCheckSummaryDto$zodSchema)
      .optional().describe("Background check requests for this member"),
    createdAt: z.iso.datetime({ offset: true }).describe(
      "When the member was created",
    ),
    deactivated: z.boolean().describe("Whether member is deactivated"),
    department: z.string().describe(
      "Member department. May be one of the built-in values (none, admin, gov, hr, it, itsm, qms) or a custom department name.",
    ),
    fleetDmLabelId: z.lazy(() => PeopleResponseDtoFleetDmLabelId$zodSchema)
      .nullable().describe("FleetDM label ID for member devices"),
    id: z.string().describe("Member ID"),
    isActive: z.boolean().describe("Whether member is active"),
    jobTitle: z.lazy(() => JobTitle$zodSchema).nullable().describe(
      "Job title for the member",
    ),
    organizationId: z.string().describe(
      "Organization ID this member belongs to",
    ),
    role: z.string().describe("Member role"),
    user: UserResponseDto$zodSchema.describe("User information"),
    userId: z.string().describe("User ID associated with member"),
  });
