/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PeopleControllerGetMentionableMembersV1Request = {
  resource: string;
};

export const PeopleControllerGetMentionableMembersV1Request$zodSchema:
  z.ZodType<PeopleControllerGetMentionableMembersV1Request> = z.object({
    resource: z.string(),
  });
