/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerGetPdfSignedUrlV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId?: string | undefined;
};

export const PoliciesControllerGetPdfSignedUrlV1Request$zodSchema: z.ZodType<
  PoliciesControllerGetPdfSignedUrlV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  versionId: z.string().optional(),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});
