/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PolicyResponseDto,
  PolicyResponseDto$zodSchema,
} from "./policyresponsedto.js";

export type PoliciesControllerGetPolicyV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PoliciesControllerGetPolicyV1Security$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type PoliciesControllerGetPolicyV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerGetPolicyV1Request$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

/**
 * Policy not found
 */
export type PoliciesControllerGetPolicyV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyV1NotFoundResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyV1NotFoundResponseBody> = z.object({
    message: z.string().optional(),
  }).describe("Policy not found");

/**
 * Unauthorized - Invalid authentication or insufficient permissions
 */
export type PoliciesControllerGetPolicyV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyV1UnauthorizedResponseBody> = z.object({
    message: z.string().optional(),
  }).describe(
    "Unauthorized - Invalid authentication or insufficient permissions",
  );

export type PoliciesControllerGetPolicyV1Response =
  | PolicyResponseDto
  | PoliciesControllerGetPolicyV1UnauthorizedResponseBody
  | PoliciesControllerGetPolicyV1NotFoundResponseBody;

export const PoliciesControllerGetPolicyV1Response$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyV1Response
> = z.union([
  PolicyResponseDto$zodSchema,
  z.lazy(() => PoliciesControllerGetPolicyV1UnauthorizedResponseBody$zodSchema),
  z.lazy(() => PoliciesControllerGetPolicyV1NotFoundResponseBody$zodSchema),
]);
