/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerGetPolicyVersionsV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionsV1Security$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type PoliciesControllerGetPolicyVersionsV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerGetPolicyVersionsV1Request$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});

/**
 * Resource not found
 */
export type PoliciesControllerGetPolicyVersionsV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionsV1NotFoundResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionsV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Resource not found");

/**
 * Unauthorized
 */
export type PoliciesControllerGetPolicyVersionsV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionsV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionsV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized");

export type PoliciesControllerGetPolicyVersionsV1Version = {};

export const PoliciesControllerGetPolicyVersionsV1Version$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Version
> = z.object({});

/**
 * Policy versions retrieved successfully
 */
export type PoliciesControllerGetPolicyVersionsV1ResponseBody = {
  versions?: Array<PoliciesControllerGetPolicyVersionsV1Version> | undefined;
  currentVersionId?: string | null | undefined;
  pendingVersionId?: string | null | undefined;
};

export const PoliciesControllerGetPolicyVersionsV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionsV1ResponseBody> = z.object({
    currentVersionId: z.string().nullable().optional(),
    pendingVersionId: z.string().nullable().optional(),
    versions: z.array(
      z.lazy(() => PoliciesControllerGetPolicyVersionsV1Version$zodSchema),
    ).optional(),
  }).describe("Policy versions retrieved successfully");

export type PoliciesControllerGetPolicyVersionsV1Response =
  | PoliciesControllerGetPolicyVersionsV1ResponseBody
  | PoliciesControllerGetPolicyVersionsV1UnauthorizedResponseBody
  | PoliciesControllerGetPolicyVersionsV1NotFoundResponseBody;

export const PoliciesControllerGetPolicyVersionsV1Response$zodSchema: z.ZodType<
  PoliciesControllerGetPolicyVersionsV1Response
> = z.union([
  z.lazy(() => PoliciesControllerGetPolicyVersionsV1ResponseBody$zodSchema),
  z.lazy(() =>
    PoliciesControllerGetPolicyVersionsV1UnauthorizedResponseBody$zodSchema
  ),
  z.lazy(() =>
    PoliciesControllerGetPolicyVersionsV1NotFoundResponseBody$zodSchema
  ),
]);
