/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerAddPolicyControlsV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
};

export const PoliciesControllerAddPolicyControlsV1Request$zodSchema: z.ZodType<
  PoliciesControllerAddPolicyControlsV1Request
> = z.object({
  id: z.string().describe("Policy ID"),
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});
