/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerSetActivePolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerSetActivePolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Resource not found
 */
export type PoliciesControllerSetActivePolicyVersionV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerSetActivePolicyVersionV1NotFoundResponseBody$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Resource not found");

/**
 * Unauthorized
 */
export type PoliciesControllerSetActivePolicyVersionV1UnauthorizedResponseBody =
  { message?: string | undefined };

export const PoliciesControllerSetActivePolicyVersionV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<
    PoliciesControllerSetActivePolicyVersionV1UnauthorizedResponseBody
  > = z.object({
    message: z.string().optional(),
  }).describe("Unauthorized");

/**
 * Invalid request
 */
export type PoliciesControllerSetActivePolicyVersionV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerSetActivePolicyVersionV1BadRequestResponseBody$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1BadRequestResponseBody> =
    z.object({
      message: z.string().optional(),
    }).describe("Invalid request");

/**
 * Active version updated
 */
export type PoliciesControllerSetActivePolicyVersionV1ResponseBody = {
  versionId?: string | undefined;
  version?: number | undefined;
};

export const PoliciesControllerSetActivePolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1ResponseBody> = z.object({
    version: z.number().optional(),
    versionId: z.string().optional(),
  }).describe("Active version updated");

export type PoliciesControllerSetActivePolicyVersionV1Response =
  | PoliciesControllerSetActivePolicyVersionV1ResponseBody
  | PoliciesControllerSetActivePolicyVersionV1BadRequestResponseBody
  | PoliciesControllerSetActivePolicyVersionV1UnauthorizedResponseBody
  | PoliciesControllerSetActivePolicyVersionV1NotFoundResponseBody;

export const PoliciesControllerSetActivePolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerSetActivePolicyVersionV1Response> = z.union([
    z.lazy(() =>
      PoliciesControllerSetActivePolicyVersionV1ResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerSetActivePolicyVersionV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerSetActivePolicyVersionV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerSetActivePolicyVersionV1NotFoundResponseBody$zodSchema
    ),
  ]);
