/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerGetPolicyVersionByIdV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionByIdV1Security$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type PoliciesControllerGetPolicyVersionByIdV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerGetPolicyVersionByIdV1Request$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Resource not found
 */
export type PoliciesControllerGetPolicyVersionByIdV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionByIdV1NotFoundResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Resource not found");

/**
 * Unauthorized
 */
export type PoliciesControllerGetPolicyVersionByIdV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerGetPolicyVersionByIdV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1UnauthorizedResponseBody> =
    z.object({
      message: z.string().optional(),
    }).describe("Unauthorized");

export type PoliciesControllerGetPolicyVersionByIdV1Version = {};

export const PoliciesControllerGetPolicyVersionByIdV1Version$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Version> = z.object({});

/**
 * Policy version retrieved successfully
 */
export type PoliciesControllerGetPolicyVersionByIdV1ResponseBody = {
  version?: PoliciesControllerGetPolicyVersionByIdV1Version | undefined;
  currentVersionId?: string | null | undefined;
  pendingVersionId?: string | null | undefined;
};

export const PoliciesControllerGetPolicyVersionByIdV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1ResponseBody> = z.object({
    currentVersionId: z.string().nullable().optional(),
    pendingVersionId: z.string().nullable().optional(),
    version: z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1Version$zodSchema
    ).optional(),
  }).describe("Policy version retrieved successfully");

export type PoliciesControllerGetPolicyVersionByIdV1Response =
  | PoliciesControllerGetPolicyVersionByIdV1ResponseBody
  | PoliciesControllerGetPolicyVersionByIdV1UnauthorizedResponseBody
  | PoliciesControllerGetPolicyVersionByIdV1NotFoundResponseBody;

export const PoliciesControllerGetPolicyVersionByIdV1Response$zodSchema:
  z.ZodType<PoliciesControllerGetPolicyVersionByIdV1Response> = z.union([
    z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1ResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerGetPolicyVersionByIdV1NotFoundResponseBody$zodSchema
    ),
  ]);
