/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PoliciesControllerDeletePolicyVersionV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1Security$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type PoliciesControllerDeletePolicyVersionV1Request = {
  xOrganizationId?: string | undefined;
  id: string;
  versionId: string;
};

export const PoliciesControllerDeletePolicyVersionV1Request$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1Request> = z.object({
    id: z.string().describe("Policy ID"),
    versionId: z.string().describe("Policy version ID"),
    xOrganizationId: z.string().describe(
      "Organization ID (required for session auth, optional for API key auth)",
    ).optional(),
  });

/**
 * Resource not found
 */
export type PoliciesControllerDeletePolicyVersionV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1NotFoundResponseBody$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1NotFoundResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Resource not found");

/**
 * Unauthorized
 */
export type PoliciesControllerDeletePolicyVersionV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1UnauthorizedResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Unauthorized");

/**
 * Invalid request
 */
export type PoliciesControllerDeletePolicyVersionV1BadRequestResponseBody = {
  message?: string | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1BadRequestResponseBody$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1BadRequestResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Invalid request");

/**
 * Version deleted
 */
export type PoliciesControllerDeletePolicyVersionV1ResponseBody = {
  deletedVersion?: number | undefined;
};

export const PoliciesControllerDeletePolicyVersionV1ResponseBody$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1ResponseBody> = z.object({
    deletedVersion: z.number().optional(),
  }).describe("Version deleted");

export type PoliciesControllerDeletePolicyVersionV1Response =
  | PoliciesControllerDeletePolicyVersionV1ResponseBody
  | PoliciesControllerDeletePolicyVersionV1BadRequestResponseBody
  | PoliciesControllerDeletePolicyVersionV1UnauthorizedResponseBody
  | PoliciesControllerDeletePolicyVersionV1NotFoundResponseBody;

export const PoliciesControllerDeletePolicyVersionV1Response$zodSchema:
  z.ZodType<PoliciesControllerDeletePolicyVersionV1Response> = z.union([
    z.lazy(() => PoliciesControllerDeletePolicyVersionV1ResponseBody$zodSchema),
    z.lazy(() =>
      PoliciesControllerDeletePolicyVersionV1BadRequestResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerDeletePolicyVersionV1UnauthorizedResponseBody$zodSchema
    ),
    z.lazy(() =>
      PoliciesControllerDeletePolicyVersionV1NotFoundResponseBody$zodSchema
    ),
  ]);
