/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PublishVersionDto = {
  versionId?: string | undefined;
  setAsActive?: boolean | undefined;
  changelog?: string | undefined;
};

export const PublishVersionDto$zodSchema: z.ZodType<PublishVersionDto> = z
  .object({
    changelog: z.string().optional().describe(
      "Optional changelog to associate with the published version",
    ),
    setAsActive: z.boolean().optional().describe(
      "Whether to set this version as the active version",
    ),
    versionId: z.string().optional().describe(
      "Version ID to publish. PASS THIS after update-version to publish your edits — omitting it publishes stale draftContent (loses your changes).",
    ),
  });
