/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type QuestionnaireControllerAnswerSingleQuestionV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const QuestionnaireControllerAnswerSingleQuestionV1Security$zodSchema:
  z.ZodType<QuestionnaireControllerAnswerSingleQuestionV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type QuestionnaireControllerAnswerSingleQuestionV1Source = {};

export const QuestionnaireControllerAnswerSingleQuestionV1Source$zodSchema:
  z.ZodType<QuestionnaireControllerAnswerSingleQuestionV1Source> = z.object({});

export type QuestionnaireControllerAnswerSingleQuestionV1Data = {
  questionIndex?: number | undefined;
  question?: string | undefined;
  answer?: string | null | undefined;
  sources?:
    | Array<QuestionnaireControllerAnswerSingleQuestionV1Source>
    | undefined;
  error?: string | null | undefined;
};

export const QuestionnaireControllerAnswerSingleQuestionV1Data$zodSchema:
  z.ZodType<QuestionnaireControllerAnswerSingleQuestionV1Data> = z.object({
    answer: z.string().nullable().optional(),
    error: z.string().nullable().optional(),
    question: z.string().optional(),
    questionIndex: z.number().optional(),
    sources: z.array(
      z.lazy(() =>
        QuestionnaireControllerAnswerSingleQuestionV1Source$zodSchema
      ),
    ).optional(),
  });

/**
 * Generated single answer result
 */
export type QuestionnaireControllerAnswerSingleQuestionV1Response = {
  success?: boolean | undefined;
  data?: QuestionnaireControllerAnswerSingleQuestionV1Data | undefined;
};

export const QuestionnaireControllerAnswerSingleQuestionV1Response$zodSchema:
  z.ZodType<QuestionnaireControllerAnswerSingleQuestionV1Response> = z.object({
    data: z.lazy(() =>
      QuestionnaireControllerAnswerSingleQuestionV1Data$zodSchema
    ).optional(),
    success: z.boolean().optional(),
  }).describe("Generated single answer result");
