/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Delete questionnaire answer
 */
export type QuestionnaireControllerDeleteAnswerV1Response = {
  success?: boolean | undefined;
  error?: string | null | undefined;
};

export const QuestionnaireControllerDeleteAnswerV1Response$zodSchema: z.ZodType<
  QuestionnaireControllerDeleteAnswerV1Response
> = z.object({
  error: z.string().nullable().optional(),
  success: z.boolean().optional(),
}).describe("Delete questionnaire answer");
