/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type QuestionnaireControllerDeleteByIdV1Request = { id: string };

export const QuestionnaireControllerDeleteByIdV1Request$zodSchema: z.ZodType<
  QuestionnaireControllerDeleteByIdV1Request
> = z.object({
  id: z.string(),
});
