/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { ClosedEnum } from "../types/enums.js";

export type QuestionnaireControllerParseQuestionnaireUploadV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const QuestionnaireControllerParseQuestionnaireUploadV1Security$zodSchema:
  z.ZodType<QuestionnaireControllerParseQuestionnaireUploadV1Security> = z
    .object({
      apikey: z.string().describe("API key for authentication").optional(),
      oauth2: z.string().describe(
        "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
      ).optional(),
    });

export type QuestionnaireControllerParseQuestionnaireUploadV1File = {
  fileName: string;
  content: Uint8Array | string;
};

export const QuestionnaireControllerParseQuestionnaireUploadV1File$zodSchema:
  z.ZodType<QuestionnaireControllerParseQuestionnaireUploadV1File> = z.object({
    content: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    fileName: z.string(),
  });

/**
 * Output format (defaults to XLSX)
 */
export const QuestionnaireControllerParseQuestionnaireUploadV1Format = {
  Pdf: "pdf",
  Csv: "csv",
  Xlsx: "xlsx",
} as const;
/**
 * Output format (defaults to XLSX)
 */
export type QuestionnaireControllerParseQuestionnaireUploadV1Format =
  ClosedEnum<typeof QuestionnaireControllerParseQuestionnaireUploadV1Format>;

export const QuestionnaireControllerParseQuestionnaireUploadV1Format$zodSchema =
  z.enum([
    "pdf",
    "csv",
    "xlsx",
  ]).describe("Output format (defaults to XLSX)");

/**
 * Indicates if the request originated from our UI (internal) or trust portal (external).
 */
export const QuestionnaireControllerParseQuestionnaireUploadV1Source = {
  Internal: "internal",
  External: "external",
} as const;
/**
 * Indicates if the request originated from our UI (internal) or trust portal (external).
 */
export type QuestionnaireControllerParseQuestionnaireUploadV1Source =
  ClosedEnum<typeof QuestionnaireControllerParseQuestionnaireUploadV1Source>;

export const QuestionnaireControllerParseQuestionnaireUploadV1Source$zodSchema =
  z.enum([
    "internal",
    "external",
  ]).describe(
    "Indicates if the request originated from our UI (internal) or trust portal (external).",
  );

export type QuestionnaireControllerParseQuestionnaireUploadV1Request = {
  file: QuestionnaireControllerParseQuestionnaireUploadV1File | Blob;
  organizationId: string;
  format?: QuestionnaireControllerParseQuestionnaireUploadV1Format | undefined;
  source?: QuestionnaireControllerParseQuestionnaireUploadV1Source | undefined;
};

export const QuestionnaireControllerParseQuestionnaireUploadV1Request$zodSchema:
  z.ZodType<QuestionnaireControllerParseQuestionnaireUploadV1Request> = z
    .object({
      file: z.lazy(() =>
        QuestionnaireControllerParseQuestionnaireUploadV1File$zodSchema
      ).describe("Questionnaire file (PDF, image, XLSX, CSV, TXT)"),
      format: QuestionnaireControllerParseQuestionnaireUploadV1Format$zodSchema
        .default("xlsx").describe("Output format (defaults to XLSX)"),
      organizationId: z.string().describe(
        "Organization to use for generating answers",
      ),
      source: QuestionnaireControllerParseQuestionnaireUploadV1Source$zodSchema
        .default("internal").describe(
          "Indicates if the request originated from our UI (internal) or trust portal (external).",
        ),
    });
