/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RequestPolicyPdfUploadUrlDto = {
  versionId?: string | undefined;
  fileName: string;
  fileType: string;
};

export const RequestPolicyPdfUploadUrlDto$zodSchema: z.ZodType<
  RequestPolicyPdfUploadUrlDto
> = z.object({
  fileName: z.string().describe(
    "Filename of the PDF (e.g., \"policy-v1.pdf\"). Non-alphanumeric characters will be replaced with underscores when storing in S3.",
  ),
  fileType: z.string().describe(
    "MIME type of the file. Must be \"application/pdf\" — the presigned URL enforces this at upload time.",
  ),
  versionId: z.string().optional().describe(
    "Optional version ID to attach the PDF to. Omit to attach the PDF at the policy level (legacy path).",
  ),
});
