/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RevokeGrantDto = { reason: string };

export const RevokeGrantDto$zodSchema: z.ZodType<RevokeGrantDto> = z.object({
  reason: z.string(),
});
