/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { UpdateRiskDto, UpdateRiskDto$zodSchema } from "./updateriskdto.js";

export type RisksControllerUpdateRiskV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const RisksControllerUpdateRiskV1Security$zodSchema: z.ZodType<
  RisksControllerUpdateRiskV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type RisksControllerUpdateRiskV1Request = {
  id: string;
  body: UpdateRiskDto;
};

export const RisksControllerUpdateRiskV1Request$zodSchema: z.ZodType<
  RisksControllerUpdateRiskV1Request
> = z.object({
  body: UpdateRiskDto$zodSchema.describe("Risk update data"),
  id: z.string().describe("Risk ID"),
});

/**
 * Internal server error
 */
export type RisksControllerUpdateRiskV1InternalServerErrorResponseBody = {
  message?: string | undefined;
};

export const RisksControllerUpdateRiskV1InternalServerErrorResponseBody$zodSchema:
  z.ZodType<RisksControllerUpdateRiskV1InternalServerErrorResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Internal server error");

/**
 * Risk not found
 */
export type RisksControllerUpdateRiskV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const RisksControllerUpdateRiskV1NotFoundResponseBody$zodSchema:
  z.ZodType<RisksControllerUpdateRiskV1NotFoundResponseBody> = z.object({
    message: z.string().optional(),
  }).describe("Risk not found");

/**
 * Unauthorized - Invalid authentication or insufficient permissions
 */
export type RisksControllerUpdateRiskV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const RisksControllerUpdateRiskV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<RisksControllerUpdateRiskV1UnauthorizedResponseBody> = z.object({
    message: z.string().optional(),
  }).describe(
    "Unauthorized - Invalid authentication or insufficient permissions",
  );

/**
 * Bad request - Invalid input data
 */
export type RisksControllerUpdateRiskV1BadRequestResponseBody = {
  message?: Array<string> | undefined;
  error?: string | undefined;
  statusCode?: number | undefined;
};

export const RisksControllerUpdateRiskV1BadRequestResponseBody$zodSchema:
  z.ZodType<RisksControllerUpdateRiskV1BadRequestResponseBody> = z.object({
    error: z.string().optional(),
    message: z.array(z.string()).optional(),
    statusCode: z.number().optional(),
  }).describe("Bad request - Invalid input data");

export const RisksControllerUpdateRiskV1Category = {
  Customer: "customer",
  Governance: "governance",
  Operations: "operations",
  Other: "other",
  People: "people",
  Regulatory: "regulatory",
  Reporting: "reporting",
  Resilience: "resilience",
  Technology: "technology",
  VendorManagement: "vendor_management",
} as const;
export type RisksControllerUpdateRiskV1Category = ClosedEnum<
  typeof RisksControllerUpdateRiskV1Category
>;

export const RisksControllerUpdateRiskV1Category$zodSchema = z.enum([
  "customer",
  "governance",
  "operations",
  "other",
  "people",
  "regulatory",
  "reporting",
  "resilience",
  "technology",
  "vendor_management",
]);

export const RisksControllerUpdateRiskV1Department = {
  None: "none",
  Admin: "admin",
  Gov: "gov",
  Hr: "hr",
  It: "it",
  Itsm: "itsm",
  Qms: "qms",
} as const;
export type RisksControllerUpdateRiskV1Department = ClosedEnum<
  typeof RisksControllerUpdateRiskV1Department
>;

export const RisksControllerUpdateRiskV1Department$zodSchema = z.enum([
  "none",
  "admin",
  "gov",
  "hr",
  "it",
  "itsm",
  "qms",
]);

export const RisksControllerUpdateRiskV1Status = {
  Open: "open",
  Pending: "pending",
  Closed: "closed",
  Archived: "archived",
} as const;
export type RisksControllerUpdateRiskV1Status = ClosedEnum<
  typeof RisksControllerUpdateRiskV1Status
>;

export const RisksControllerUpdateRiskV1Status$zodSchema = z.enum([
  "open",
  "pending",
  "closed",
  "archived",
]);

export const RisksControllerUpdateRiskV1Likelihood = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
export type RisksControllerUpdateRiskV1Likelihood = ClosedEnum<
  typeof RisksControllerUpdateRiskV1Likelihood
>;

export const RisksControllerUpdateRiskV1Likelihood$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]);

export const RisksControllerUpdateRiskV1Impact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
export type RisksControllerUpdateRiskV1Impact = ClosedEnum<
  typeof RisksControllerUpdateRiskV1Impact
>;

export const RisksControllerUpdateRiskV1Impact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]);

export const RisksControllerUpdateRiskV1ResidualLikelihood = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
export type RisksControllerUpdateRiskV1ResidualLikelihood = ClosedEnum<
  typeof RisksControllerUpdateRiskV1ResidualLikelihood
>;

export const RisksControllerUpdateRiskV1ResidualLikelihood$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]);

export const RisksControllerUpdateRiskV1ResidualImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
export type RisksControllerUpdateRiskV1ResidualImpact = ClosedEnum<
  typeof RisksControllerUpdateRiskV1ResidualImpact
>;

export const RisksControllerUpdateRiskV1ResidualImpact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]);

export const RisksControllerUpdateRiskV1TreatmentStrategy = {
  Accept: "accept",
  Avoid: "avoid",
  Mitigate: "mitigate",
  Transfer: "transfer",
} as const;
export type RisksControllerUpdateRiskV1TreatmentStrategy = ClosedEnum<
  typeof RisksControllerUpdateRiskV1TreatmentStrategy
>;

export const RisksControllerUpdateRiskV1TreatmentStrategy$zodSchema = z.enum([
  "accept",
  "avoid",
  "mitigate",
  "transfer",
]);

/**
 * How the request was authenticated
 */
export const RisksControllerUpdateRiskV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type RisksControllerUpdateRiskV1AuthType = ClosedEnum<
  typeof RisksControllerUpdateRiskV1AuthType
>;

export const RisksControllerUpdateRiskV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

/**
 * User information (only for session auth)
 */
export type RisksControllerUpdateRiskV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const RisksControllerUpdateRiskV1AuthenticatedUser$zodSchema: z.ZodType<
  RisksControllerUpdateRiskV1AuthenticatedUser
> = z.object({
  email: z.string().optional(),
  id: z.string().optional(),
}).describe("User information (only for session auth)");

/**
 * Risk updated successfully
 */
export type RisksControllerUpdateRiskV1ResponseBody = {
  id?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  category?: RisksControllerUpdateRiskV1Category | undefined;
  department?: RisksControllerUpdateRiskV1Department | null | undefined;
  status?: RisksControllerUpdateRiskV1Status | undefined;
  likelihood?: RisksControllerUpdateRiskV1Likelihood | undefined;
  impact?: RisksControllerUpdateRiskV1Impact | undefined;
  residualLikelihood?:
    | RisksControllerUpdateRiskV1ResidualLikelihood
    | undefined;
  residualImpact?: RisksControllerUpdateRiskV1ResidualImpact | undefined;
  treatmentStrategyDescription?: string | null | undefined;
  treatmentStrategy?: RisksControllerUpdateRiskV1TreatmentStrategy | undefined;
  organizationId?: string | undefined;
  assigneeId?: string | null | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  authType?: RisksControllerUpdateRiskV1AuthType | undefined;
  authenticatedUser?: RisksControllerUpdateRiskV1AuthenticatedUser | undefined;
};

export const RisksControllerUpdateRiskV1ResponseBody$zodSchema: z.ZodType<
  RisksControllerUpdateRiskV1ResponseBody
> = z.object({
  assigneeId: z.string().nullable().optional().describe(
    "ID of the user assigned to this risk",
  ),
  authType: RisksControllerUpdateRiskV1AuthType$zodSchema.optional().describe(
    "How the request was authenticated",
  ),
  authenticatedUser: z.lazy(() =>
    RisksControllerUpdateRiskV1AuthenticatedUser$zodSchema
  ).optional().describe("User information (only for session auth)"),
  category: RisksControllerUpdateRiskV1Category$zodSchema.optional(),
  createdAt: z.iso.datetime({ offset: true }).optional().describe(
    "When the risk was created",
  ),
  department: RisksControllerUpdateRiskV1Department$zodSchema.nullable()
    .optional(),
  description: z.string().optional().describe("Risk description"),
  id: z.string().optional().describe("Risk ID"),
  impact: RisksControllerUpdateRiskV1Impact$zodSchema.optional(),
  likelihood: RisksControllerUpdateRiskV1Likelihood$zodSchema.optional(),
  organizationId: z.string().optional(),
  residualImpact: RisksControllerUpdateRiskV1ResidualImpact$zodSchema
    .optional(),
  residualLikelihood: RisksControllerUpdateRiskV1ResidualLikelihood$zodSchema
    .optional(),
  status: RisksControllerUpdateRiskV1Status$zodSchema.optional(),
  title: z.string().optional().describe("Risk title"),
  treatmentStrategy: RisksControllerUpdateRiskV1TreatmentStrategy$zodSchema
    .optional(),
  treatmentStrategyDescription: z.string().nullable().optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional().describe(
    "When the risk was last updated",
  ),
}).describe("Risk updated successfully");

export type RisksControllerUpdateRiskV1Response =
  | RisksControllerUpdateRiskV1ResponseBody
  | RisksControllerUpdateRiskV1BadRequestResponseBody
  | RisksControllerUpdateRiskV1UnauthorizedResponseBody
  | RisksControllerUpdateRiskV1NotFoundResponseBody
  | RisksControllerUpdateRiskV1InternalServerErrorResponseBody;

export const RisksControllerUpdateRiskV1Response$zodSchema: z.ZodType<
  RisksControllerUpdateRiskV1Response
> = z.union([
  z.lazy(() => RisksControllerUpdateRiskV1ResponseBody$zodSchema),
  z.lazy(() => RisksControllerUpdateRiskV1BadRequestResponseBody$zodSchema),
  z.lazy(() => RisksControllerUpdateRiskV1UnauthorizedResponseBody$zodSchema),
  z.lazy(() => RisksControllerUpdateRiskV1NotFoundResponseBody$zodSchema),
  z.lazy(() =>
    RisksControllerUpdateRiskV1InternalServerErrorResponseBody$zodSchema
  ),
]);
