/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  UpdateBuiltInObligationsDto,
  UpdateBuiltInObligationsDto$zodSchema,
} from "./updatebuiltinobligationsdto.js";

export type RolesControllerUpdateBuiltInObligationsV1Request = {
  name: string;
  body: UpdateBuiltInObligationsDto;
};

export const RolesControllerUpdateBuiltInObligationsV1Request$zodSchema:
  z.ZodType<RolesControllerUpdateBuiltInObligationsV1Request> = z.object({
    body: UpdateBuiltInObligationsDto$zodSchema,
    name: z.string().describe("Built-in role name"),
  });

export type RolesControllerUpdateBuiltInObligationsV1Obligations = {
  compliance?: boolean | undefined;
};

export const RolesControllerUpdateBuiltInObligationsV1Obligations$zodSchema:
  z.ZodType<RolesControllerUpdateBuiltInObligationsV1Obligations> = z.object({
    compliance: z.boolean().optional(),
  });

/**
 * Obligations updated
 */
export type RolesControllerUpdateBuiltInObligationsV1Response = {
  name?: string | undefined;
  obligations?:
    | RolesControllerUpdateBuiltInObligationsV1Obligations
    | undefined;
};

export const RolesControllerUpdateBuiltInObligationsV1Response$zodSchema:
  z.ZodType<RolesControllerUpdateBuiltInObligationsV1Response> = z.object({
    name: z.string().optional(),
    obligations: z.lazy(() =>
      RolesControllerUpdateBuiltInObligationsV1Obligations$zodSchema
    ).optional(),
  }).describe("Obligations updated");
