/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BuiltInRole = {
  name?: string | undefined;
  isBuiltIn?: boolean | undefined;
  description?: string | undefined;
};

export const BuiltInRole$zodSchema: z.ZodType<BuiltInRole> = z.object({
  description: z.string().optional(),
  isBuiltIn: z.boolean().optional(),
  name: z.string().optional(),
});

export type RolesControllerListRolesV1Permissions = {};

export const RolesControllerListRolesV1Permissions$zodSchema: z.ZodType<
  RolesControllerListRolesV1Permissions
> = z.object({});

export type CustomRole = {
  id?: string | undefined;
  name?: string | undefined;
  permissions?: RolesControllerListRolesV1Permissions | undefined;
  isBuiltIn?: boolean | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const CustomRole$zodSchema: z.ZodType<CustomRole> = z.object({
  createdAt: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  isBuiltIn: z.boolean().optional(),
  name: z.string().optional(),
  permissions: z.lazy(() => RolesControllerListRolesV1Permissions$zodSchema)
    .optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
});

/**
 * List of roles
 */
export type RolesControllerListRolesV1Response = {
  builtInRoles?: Array<BuiltInRole> | undefined;
  customRoles?: Array<CustomRole> | undefined;
};

export const RolesControllerListRolesV1Response$zodSchema: z.ZodType<
  RolesControllerListRolesV1Response
> = z.object({
  builtInRoles: z.array(z.lazy(() => BuiltInRole$zodSchema)).optional(),
  customRoles: z.array(z.lazy(() => CustomRole$zodSchema)).optional(),
}).describe("List of roles");
