/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UpdateRoleDto, UpdateRoleDto$zodSchema } from "./updateroledto.js";

export type RolesControllerUpdateRoleV1Request = {
  roleId: string;
  body: UpdateRoleDto;
};

export const RolesControllerUpdateRoleV1Request$zodSchema: z.ZodType<
  RolesControllerUpdateRoleV1Request
> = z.object({
  body: UpdateRoleDto$zodSchema,
  roleId: z.string().describe("Role ID"),
});

export type RolesControllerUpdateRoleV1Permissions = {};

export const RolesControllerUpdateRoleV1Permissions$zodSchema: z.ZodType<
  RolesControllerUpdateRoleV1Permissions
> = z.object({});

/**
 * Role updated successfully
 */
export type RolesControllerUpdateRoleV1Response = {
  id?: string | undefined;
  name?: string | undefined;
  permissions?: RolesControllerUpdateRoleV1Permissions | undefined;
  isBuiltIn?: boolean | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
};

export const RolesControllerUpdateRoleV1Response$zodSchema: z.ZodType<
  RolesControllerUpdateRoleV1Response
> = z.object({
  createdAt: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  isBuiltIn: z.boolean().optional(),
  name: z.string().optional(),
  permissions: z.lazy(() => RolesControllerUpdateRoleV1Permissions$zodSchema)
    .optional(),
  updatedAt: z.iso.datetime({ offset: true }).optional(),
}).describe("Role updated successfully");
