/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RunChecksDto = { checkId?: string | undefined };

export const RunChecksDto$zodSchema: z.ZodType<RunChecksDto> = z.object({
  checkId: z.string().optional().describe(
    "Specific check ID to run. Omit to run ALL available checks for the connection (matches the provider manifest).",
  ),
});
