/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RunCheckForTaskDto = { connectionId: string; checkId: string };

export const RunCheckForTaskDto$zodSchema: z.ZodType<RunCheckForTaskDto> = z
  .object({
    checkId: z.string().describe(
      "ID of the integration check to run (from the provider manifest — call list-checks-for-task to find available ones).",
    ),
    connectionId: z.string().describe(
      "ID of the integration connection that owns the check (call list-connections to find it).",
    ),
  });
