/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Provider slug to use for employee sync (must have the "sync" capability in its manifest — call list-providers to see options). Pass null or omit the field to disable employee sync for this org.
 */
export type Provider = {};

export const Provider$zodSchema: z.ZodType<Provider> = z.object({}).describe(
  "Provider slug to use for employee sync (must have the \"sync\" capability in its manifest — call list-providers to see options). Pass null or omit the field to disable employee sync for this org.",
);

export type SetEmployeeSyncProviderDto = {
  provider?: Provider | null | undefined;
};

export const SetEmployeeSyncProviderDto$zodSchema: z.ZodType<
  SetEmployeeSyncProviderDto
> = z.object({
  provider: z.lazy(() => Provider$zodSchema).nullable().optional().describe(
    "Provider slug to use for employee sync (must have the \"sync\" capability in its manifest — call list-providers to see options). Pass null or omit the field to disable employee sync for this org.",
  ),
});
