/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SyncControllerSyncDynamicProviderEmployeesV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const SyncControllerSyncDynamicProviderEmployeesV1Security$zodSchema:
  z.ZodType<SyncControllerSyncDynamicProviderEmployeesV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type SyncControllerSyncDynamicProviderEmployeesV1Request = {
  providerSlug: string;
  connectionId: string;
};

export const SyncControllerSyncDynamicProviderEmployeesV1Request$zodSchema:
  z.ZodType<SyncControllerSyncDynamicProviderEmployeesV1Request> = z.object({
    connectionId: z.string(),
    providerSlug: z.string(),
  });
