/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SyncFrameworkDto = {};

export const SyncFrameworkDto$zodSchema: z.ZodType<SyncFrameworkDto> = z.object(
  {},
);
