/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SyncControllerSyncJumpCloudEmployeesV1Request = {
  connectionId: string;
};

export const SyncControllerSyncJumpCloudEmployeesV1Request$zodSchema: z.ZodType<
  SyncControllerSyncJumpCloudEmployeesV1Request
> = z.object({
  connectionId: z.string(),
});
