/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SyncControllerGetAvailableSyncProvidersV1Request = {
  syncType: string;
};

export const SyncControllerGetAvailableSyncProvidersV1Request$zodSchema:
  z.ZodType<SyncControllerGetAvailableSyncProvidersV1Request> = z.object({
    syncType: z.string(),
  });
