/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SyncControllerSyncDynamicProviderEmployeesV1Request = {
  providerSlug: string;
  connectionId: string;
};

export const SyncControllerSyncDynamicProviderEmployeesV1Request$zodSchema:
  z.ZodType<SyncControllerSyncDynamicProviderEmployeesV1Request> = z.object({
    connectionId: z.string(),
    providerSlug: z.string(),
  });
