/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TaskManagementControllerDeleteTaskItemAttachmentV1Request = {
  attachmentId: string;
};

export const TaskManagementControllerDeleteTaskItemAttachmentV1Request$zodSchema:
  z.ZodType<TaskManagementControllerDeleteTaskItemAttachmentV1Request> = z
    .object({
      attachmentId: z.string().describe("Attachment ID"),
    });
