/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Task status
 */
export const TaskResponseDtoStatus = {
  Todo: "todo",
  InProgress: "in_progress",
  Done: "done",
  Blocked: "blocked",
} as const;
/**
 * Task status
 */
export type TaskResponseDtoStatus = ClosedEnum<typeof TaskResponseDtoStatus>;

export const TaskResponseDtoStatus$zodSchema = z.enum([
  "todo",
  "in_progress",
  "done",
  "blocked",
]).describe("Task status");

/**
 * Task template ID
 */
export type TaskTemplateId = {};

export const TaskTemplateId$zodSchema: z.ZodType<TaskTemplateId> = z.object({})
  .describe("Task template ID");

/**
 * Cadence for running the integration check attached to this task
 */
export const IntegrationScheduleFrequency = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
  Quarterly: "quarterly",
  Yearly: "yearly",
} as const;
/**
 * Cadence for running the integration check attached to this task
 */
export type IntegrationScheduleFrequency = ClosedEnum<
  typeof IntegrationScheduleFrequency
>;

export const IntegrationScheduleFrequency$zodSchema = z.enum([
  "daily",
  "weekly",
  "monthly",
  "quarterly",
  "yearly",
]).describe("Cadence for running the integration check attached to this task");

/**
 * Last successful integration check run timestamp
 */
export type IntegrationLastRunAt = {};

export const IntegrationLastRunAt$zodSchema: z.ZodType<IntegrationLastRunAt> = z
  .object({}).describe("Last successful integration check run timestamp");

export type TaskResponseDto = {
  id: string;
  title: string;
  description?: string | undefined;
  status: TaskResponseDtoStatus;
  createdAt: string;
  updatedAt: string;
  taskTemplateId?: TaskTemplateId | null | undefined;
  integrationScheduleFrequency: IntegrationScheduleFrequency;
  integrationLastRunAt?: IntegrationLastRunAt | null | undefined;
};

export const TaskResponseDto$zodSchema: z.ZodType<TaskResponseDto> = z.object({
  createdAt: z.iso.datetime({ offset: true }).describe(
    "Task creation timestamp",
  ),
  description: z.string().optional().describe("Task description"),
  id: z.string().describe("Unique identifier for the task"),
  integrationLastRunAt: z.lazy(() => IntegrationLastRunAt$zodSchema).nullable()
    .optional().describe("Last successful integration check run timestamp"),
  integrationScheduleFrequency: IntegrationScheduleFrequency$zodSchema.describe(
    "Cadence for running the integration check attached to this task",
  ),
  status: TaskResponseDtoStatus$zodSchema.describe("Task status"),
  taskTemplateId: z.lazy(() => TaskTemplateId$zodSchema).nullable().optional()
    .describe("Task template ID"),
  title: z.string().describe("Task title"),
  updatedAt: z.iso.datetime({ offset: true }).describe(
    "Task last update timestamp",
  ),
});
