/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ToggleCheckForTaskDto,
  ToggleCheckForTaskDto$zodSchema,
} from "./togglecheckfortaskdto.js";

export type TaskIntegrationsControllerReconnectCheckToTaskV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const TaskIntegrationsControllerReconnectCheckToTaskV1Security$zodSchema:
  z.ZodType<TaskIntegrationsControllerReconnectCheckToTaskV1Security> = z
    .object({
      apikey: z.string().describe("API key for authentication").optional(),
      oauth2: z.string().describe(
        "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
      ).optional(),
    });

export type TaskIntegrationsControllerReconnectCheckToTaskV1Request = {
  taskId: string;
  body: ToggleCheckForTaskDto;
};

export const TaskIntegrationsControllerReconnectCheckToTaskV1Request$zodSchema:
  z.ZodType<TaskIntegrationsControllerReconnectCheckToTaskV1Request> = z.object(
    {
      body: ToggleCheckForTaskDto$zodSchema,
      taskId: z.string(),
    },
  );
