/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TaskManagementControllerDeleteTaskItemAttachmentV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const TaskManagementControllerDeleteTaskItemAttachmentV1Security$zodSchema:
  z.ZodType<TaskManagementControllerDeleteTaskItemAttachmentV1Security> = z
    .object({
      apikey: z.string().describe("API key for authentication").optional(),
      oauth2: z.string().describe(
        "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
      ).optional(),
    });

export type TaskManagementControllerDeleteTaskItemAttachmentV1Request = {
  attachmentId: string;
};

export const TaskManagementControllerDeleteTaskItemAttachmentV1Request$zodSchema:
  z.ZodType<TaskManagementControllerDeleteTaskItemAttachmentV1Request> = z
    .object({
      attachmentId: z.string().describe("Attachment ID"),
    });
