/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TasksControllerApproveTaskV1Request = { taskId: string };

export const TasksControllerApproveTaskV1Request$zodSchema: z.ZodType<
  TasksControllerApproveTaskV1Request
> = z.object({
  taskId: z.string().describe("Unique task identifier"),
});
