/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TasksControllerGetTaskPoliciesV1Request = { taskId: string };

export const TasksControllerGetTaskPoliciesV1Request$zodSchema: z.ZodType<
  TasksControllerGetTaskPoliciesV1Request
> = z.object({
  taskId: z.string().describe("Unique task identifier"),
});
