/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TasksControllerBulkSubmitForReviewV1Request = {
  taskIds: Array<string>;
  approverId: string;
};

export const TasksControllerBulkSubmitForReviewV1Request$zodSchema: z.ZodType<
  TasksControllerBulkSubmitForReviewV1Request
> = z.object({
  approverId: z.string().describe("Member ID of the approver"),
  taskIds: z.array(z.string()),
});
