/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type TasksControllerCreateTaskV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const TasksControllerCreateTaskV1Security$zodSchema: z.ZodType<
  TasksControllerCreateTaskV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export const TasksControllerCreateTaskV1Frequency = {
  Daily: "daily",
  Weekly: "weekly",
  Monthly: "monthly",
  Quarterly: "quarterly",
  Yearly: "yearly",
} as const;
export type TasksControllerCreateTaskV1Frequency = ClosedEnum<
  typeof TasksControllerCreateTaskV1Frequency
>;

export const TasksControllerCreateTaskV1Frequency$zodSchema = z.enum([
  "daily",
  "weekly",
  "monthly",
  "quarterly",
  "yearly",
]);

export const TasksControllerCreateTaskV1Department = {
  None: "none",
  Admin: "admin",
  Gov: "gov",
  Hr: "hr",
  It: "it",
  Itsm: "itsm",
  Qms: "qms",
} as const;
export type TasksControllerCreateTaskV1Department = ClosedEnum<
  typeof TasksControllerCreateTaskV1Department
>;

export const TasksControllerCreateTaskV1Department$zodSchema = z.enum([
  "none",
  "admin",
  "gov",
  "hr",
  "it",
  "itsm",
  "qms",
]);

export type TasksControllerCreateTaskV1Request = {
  title: string;
  description: string;
  assigneeId?: string | null | undefined;
  frequency?: TasksControllerCreateTaskV1Frequency | null | undefined;
  department?: TasksControllerCreateTaskV1Department | null | undefined;
  controlIds?: Array<string> | undefined;
  taskTemplateId?: string | null | undefined;
  vendorId?: string | null | undefined;
};

export const TasksControllerCreateTaskV1Request$zodSchema: z.ZodType<
  TasksControllerCreateTaskV1Request
> = z.object({
  assigneeId: z.string().nullable().optional(),
  controlIds: z.array(z.string()).optional(),
  department: TasksControllerCreateTaskV1Department$zodSchema.nullable()
    .optional(),
  description: z.string(),
  frequency: TasksControllerCreateTaskV1Frequency$zodSchema.nullable()
    .optional(),
  taskTemplateId: z.string().nullable().optional(),
  title: z.string(),
  vendorId: z.string().nullable().optional().describe(
    "Vendor ID to connect this task to",
  ),
});
