/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type TasksControllerReorderTasksV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const TasksControllerReorderTasksV1Security$zodSchema: z.ZodType<
  TasksControllerReorderTasksV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export const TasksControllerReorderTasksV1Status = {
  Todo: "todo",
  InProgress: "in_progress",
  InReview: "in_review",
  Done: "done",
  NotRelevant: "not_relevant",
  Failed: "failed",
} as const;
export type TasksControllerReorderTasksV1Status = ClosedEnum<
  typeof TasksControllerReorderTasksV1Status
>;

export const TasksControllerReorderTasksV1Status$zodSchema = z.enum([
  "todo",
  "in_progress",
  "in_review",
  "done",
  "not_relevant",
  "failed",
]);

export type Update = {
  id: string;
  order: number;
  status: TasksControllerReorderTasksV1Status;
};

export const Update$zodSchema: z.ZodType<Update> = z.object({
  id: z.string(),
  order: z.number(),
  status: TasksControllerReorderTasksV1Status$zodSchema,
});

export type TasksControllerReorderTasksV1Request = { updates: Array<Update> };

export const TasksControllerReorderTasksV1Request$zodSchema: z.ZodType<
  TasksControllerReorderTasksV1Request
> = z.object({
  updates: z.array(z.lazy(() => Update$zodSchema)),
});
