/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrainingControllerMarkVideoCompleteV1Request = { videoId: string };

export const TrainingControllerMarkVideoCompleteV1Request$zodSchema: z.ZodType<
  TrainingControllerMarkVideoCompleteV1Request
> = z.object({
  videoId: z.string(),
});
