/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustPortalControllerListVendorsV1Request = {
  all?: string | undefined;
};

export const TrustPortalControllerListVendorsV1Request$zodSchema: z.ZodType<
  TrustPortalControllerListVendorsV1Request
> = z.object({
  all: z.string().describe("When true, returns all org vendors with sync")
    .optional(),
});
