/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TrustPortalControllerUpdateCustomFrameworkV1Status2 = {
  Started: "started",
  InProgress: "in_progress",
  Compliant: "compliant",
} as const;
export type TrustPortalControllerUpdateCustomFrameworkV1Status2 = ClosedEnum<
  typeof TrustPortalControllerUpdateCustomFrameworkV1Status2
>;

export const TrustPortalControllerUpdateCustomFrameworkV1Status2$zodSchema = z
  .enum([
    "started",
    "in_progress",
    "compliant",
  ]);

export const TrustPortalControllerUpdateCustomFrameworkV1Status1 = {
  Started: "started",
  InProgress: "in_progress",
  Compliant: "compliant",
} as const;
export type TrustPortalControllerUpdateCustomFrameworkV1Status1 = ClosedEnum<
  typeof TrustPortalControllerUpdateCustomFrameworkV1Status1
>;

export const TrustPortalControllerUpdateCustomFrameworkV1Status1$zodSchema = z
  .enum([
    "started",
    "in_progress",
    "compliant",
  ]);

export type TrustPortalControllerUpdateCustomFrameworkV1RequestBody2 = {
  customFrameworkId: string;
  enabled?: boolean | undefined;
  status: TrustPortalControllerUpdateCustomFrameworkV1Status2;
};

export const TrustPortalControllerUpdateCustomFrameworkV1RequestBody2$zodSchema:
  z.ZodType<TrustPortalControllerUpdateCustomFrameworkV1RequestBody2> = z
    .object({
      customFrameworkId: z.string(),
      enabled: z.boolean().optional(),
      status: TrustPortalControllerUpdateCustomFrameworkV1Status2$zodSchema,
    });

export type TrustPortalControllerUpdateCustomFrameworkV1RequestBody1 = {
  customFrameworkId: string;
  enabled: boolean;
  status?: TrustPortalControllerUpdateCustomFrameworkV1Status1 | undefined;
};

export const TrustPortalControllerUpdateCustomFrameworkV1RequestBody1$zodSchema:
  z.ZodType<TrustPortalControllerUpdateCustomFrameworkV1RequestBody1> = z
    .object({
      customFrameworkId: z.string(),
      enabled: z.boolean(),
      status: TrustPortalControllerUpdateCustomFrameworkV1Status1$zodSchema
        .optional(),
    });

/**
 * At least one of `enabled` or `status` must be provided.
 */
export type TrustPortalControllerUpdateCustomFrameworkV1Request =
  | TrustPortalControllerUpdateCustomFrameworkV1RequestBody1
  | TrustPortalControllerUpdateCustomFrameworkV1RequestBody2;

export const TrustPortalControllerUpdateCustomFrameworkV1Request$zodSchema:
  z.ZodType<TrustPortalControllerUpdateCustomFrameworkV1Request> = z.union([
    z.lazy(() =>
      TrustPortalControllerUpdateCustomFrameworkV1RequestBody1$zodSchema
    ),
    z.lazy(() =>
      TrustPortalControllerUpdateCustomFrameworkV1RequestBody2$zodSchema
    ),
  ]).describe("At least one of `enabled` or `status` must be provided.");
