/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustPortalControllerGetDomainStatusV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const TrustPortalControllerGetDomainStatusV1Security$zodSchema:
  z.ZodType<TrustPortalControllerGetDomainStatusV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type TrustPortalControllerGetDomainStatusV1Request = { domain: string };

export const TrustPortalControllerGetDomainStatusV1Request$zodSchema: z.ZodType<
  TrustPortalControllerGetDomainStatusV1Request
> = z.object({
  domain: z.string().describe("The domain name to check status for"),
});
