/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateAccessRequestDto,
  CreateAccessRequestDto$zodSchema,
} from "./createaccessrequestdto.js";

export type TrustAccessControllerCreateAccessRequestV1Request = {
  friendlyUrl: string;
  body: CreateAccessRequestDto;
};

export const TrustAccessControllerCreateAccessRequestV1Request$zodSchema:
  z.ZodType<TrustAccessControllerCreateAccessRequestV1Request> = z.object({
    body: CreateAccessRequestDto$zodSchema,
    friendlyUrl: z.string().describe(
      "Trust Portal friendly URL or Organization ID",
    ),
  });
