/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustDocumentUrlResponseDto = {
  signedUrl: string;
  fileName: string;
};

export const TrustDocumentUrlResponseDto$zodSchema: z.ZodType<
  TrustDocumentUrlResponseDto
> = z.object({
  fileName: z.string(),
  signedUrl: z.string(),
});
