/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TrustPortalControllerReorderCustomLinksV1Request = {
  organizationId: string;
  linkIds: Array<string>;
};

export const TrustPortalControllerReorderCustomLinksV1Request$zodSchema:
  z.ZodType<TrustPortalControllerReorderCustomLinksV1Request> = z.object({
    linkIds: z.array(z.string()).describe(
      "Custom link IDs in the desired display order.",
    ),
    organizationId: z.string().describe(
      "Organization that owns the trust portal. Must match the authenticated API key's organization.",
    ),
  });
