/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Employee onboard date
 */
export type OnboardDate = {};

export const OnboardDate$zodSchema: z.ZodType<OnboardDate> = z.object({})
  .describe("Employee onboard date");

/**
 * Employee offboard date
 */
export type OffboardDate = {};

export const OffboardDate$zodSchema: z.ZodType<OffboardDate> = z.object({})
  .describe("Employee offboard date");

export type UpdatePeopleDto = {
  userId?: string | undefined;
  role?: string | undefined;
  department?: string | undefined;
  isActive?: boolean | undefined;
  fleetDmLabelId?: number | undefined;
  jobTitle?: string | undefined;
  name?: string | undefined;
  email?: string | undefined;
  createdAt?: string | undefined;
  backgroundCheckExempt?: boolean | undefined;
  backgroundCheckExemptReason?: string | undefined;
  backgroundCheckExemptJustification?: string | undefined;
  onboardDate?: OnboardDate | undefined;
  offboardDate?: OffboardDate | undefined;
};

export const UpdatePeopleDto$zodSchema: z.ZodType<UpdatePeopleDto> = z.object({
  backgroundCheckExempt: z.boolean().optional().describe(
    "When true, this member is exempt from the org-level background check requirement and will count as complete in people scores.",
  ),
  backgroundCheckExemptJustification: z.string().optional().describe(
    "Free-text justification for the exemption, attached to the audit log. Cleared when the member becomes non-exempt.",
  ),
  backgroundCheckExemptReason: z.string().optional().describe(
    "Reason code for the exemption (e.g. \"contractor_with_vendor_check\", \"other\"). Persisted alongside backgroundCheckExempt and cleared when the member becomes non-exempt.",
  ),
  createdAt: z.string().optional().describe(
    "Member join date (createdAt override)",
  ),
  department: z.string().optional().describe(
    "Member department. Built-in values: none, admin, gov, hr, it, itsm, qms. Custom department names are also accepted.",
  ),
  email: z.string().optional().describe("Email of the associated user"),
  fleetDmLabelId: z.number().optional().describe(
    "FleetDM label ID for member devices",
  ),
  isActive: z.boolean().optional().describe(
    "Whether to deactivate this member (soft delete)",
  ),
  jobTitle: z.string().optional().describe("Job title for the member"),
  name: z.string().optional().describe("Name of the associated user"),
  offboardDate: z.lazy(() => OffboardDate$zodSchema).optional().describe(
    "Employee offboard date",
  ),
  onboardDate: z.lazy(() => OnboardDate$zodSchema).optional().describe(
    "Employee onboard date",
  ),
  role: z.string().optional().describe(
    "Role for the member (built-in role name or custom role ID)",
  ),
  userId: z.string().optional().describe(
    "User ID to associate with this member",
  ),
});
