/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Risk category
 */
export const UpdateRiskDtoCategory = {
  Customer: "customer",
  Fraud: "fraud",
  Governance: "governance",
  Operations: "operations",
  Other: "other",
  People: "people",
  Regulatory: "regulatory",
  Reporting: "reporting",
  Resilience: "resilience",
  Technology: "technology",
  VendorManagement: "vendor_management",
} as const;
/**
 * Risk category
 */
export type UpdateRiskDtoCategory = ClosedEnum<typeof UpdateRiskDtoCategory>;

export const UpdateRiskDtoCategory$zodSchema = z.enum([
  "customer",
  "fraud",
  "governance",
  "operations",
  "other",
  "people",
  "regulatory",
  "reporting",
  "resilience",
  "technology",
  "vendor_management",
]).describe("Risk category");

/**
 * Department responsible for the risk
 */
export const UpdateRiskDtoDepartment = {
  None: "none",
  Admin: "admin",
  Gov: "gov",
  Hr: "hr",
  It: "it",
  Itsm: "itsm",
  Qms: "qms",
} as const;
/**
 * Department responsible for the risk
 */
export type UpdateRiskDtoDepartment = ClosedEnum<
  typeof UpdateRiskDtoDepartment
>;

export const UpdateRiskDtoDepartment$zodSchema = z.enum([
  "none",
  "admin",
  "gov",
  "hr",
  "it",
  "itsm",
  "qms",
]).describe("Department responsible for the risk");

/**
 * Current status of the risk
 */
export const UpdateRiskDtoStatus = {
  Open: "open",
  Pending: "pending",
  Closed: "closed",
  Archived: "archived",
} as const;
/**
 * Current status of the risk
 */
export type UpdateRiskDtoStatus = ClosedEnum<typeof UpdateRiskDtoStatus>;

export const UpdateRiskDtoStatus$zodSchema = z.enum([
  "open",
  "pending",
  "closed",
  "archived",
]).describe("Current status of the risk");

/**
 * Likelihood of the risk occurring
 */
export const UpdateRiskDtoLikelihood = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
/**
 * Likelihood of the risk occurring
 */
export type UpdateRiskDtoLikelihood = ClosedEnum<
  typeof UpdateRiskDtoLikelihood
>;

export const UpdateRiskDtoLikelihood$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]).describe("Likelihood of the risk occurring");

/**
 * Impact if the risk materializes
 */
export const UpdateRiskDtoImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Impact if the risk materializes
 */
export type UpdateRiskDtoImpact = ClosedEnum<typeof UpdateRiskDtoImpact>;

export const UpdateRiskDtoImpact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]).describe("Impact if the risk materializes");

/**
 * Residual likelihood after treatment
 */
export const UpdateRiskDtoResidualLikelihood = {
  VeryUnlikely: "very_unlikely",
  Unlikely: "unlikely",
  Possible: "possible",
  Likely: "likely",
  VeryLikely: "very_likely",
} as const;
/**
 * Residual likelihood after treatment
 */
export type UpdateRiskDtoResidualLikelihood = ClosedEnum<
  typeof UpdateRiskDtoResidualLikelihood
>;

export const UpdateRiskDtoResidualLikelihood$zodSchema = z.enum([
  "very_unlikely",
  "unlikely",
  "possible",
  "likely",
  "very_likely",
]).describe("Residual likelihood after treatment");

/**
 * Residual impact after treatment
 */
export const UpdateRiskDtoResidualImpact = {
  Insignificant: "insignificant",
  Minor: "minor",
  Moderate: "moderate",
  Major: "major",
  Severe: "severe",
} as const;
/**
 * Residual impact after treatment
 */
export type UpdateRiskDtoResidualImpact = ClosedEnum<
  typeof UpdateRiskDtoResidualImpact
>;

export const UpdateRiskDtoResidualImpact$zodSchema = z.enum([
  "insignificant",
  "minor",
  "moderate",
  "major",
  "severe",
]).describe("Residual impact after treatment");

/**
 * Risk treatment strategy
 */
export const UpdateRiskDtoTreatmentStrategy = {
  Accept: "accept",
  Avoid: "avoid",
  Mitigate: "mitigate",
  Transfer: "transfer",
} as const;
/**
 * Risk treatment strategy
 */
export type UpdateRiskDtoTreatmentStrategy = ClosedEnum<
  typeof UpdateRiskDtoTreatmentStrategy
>;

export const UpdateRiskDtoTreatmentStrategy$zodSchema = z.enum([
  "accept",
  "avoid",
  "mitigate",
  "transfer",
]).describe("Risk treatment strategy");

export type UpdateRiskDto = {
  title?: string | undefined;
  description?: string | undefined;
  category?: UpdateRiskDtoCategory | undefined;
  department?: UpdateRiskDtoDepartment | undefined;
  status?: UpdateRiskDtoStatus | undefined;
  likelihood?: UpdateRiskDtoLikelihood | undefined;
  impact?: UpdateRiskDtoImpact | undefined;
  residualLikelihood?: UpdateRiskDtoResidualLikelihood | undefined;
  residualImpact?: UpdateRiskDtoResidualImpact | undefined;
  treatmentStrategyDescription?: string | undefined;
  treatmentStrategy?: UpdateRiskDtoTreatmentStrategy | undefined;
  assigneeId?: string | undefined;
};

export const UpdateRiskDto$zodSchema: z.ZodType<UpdateRiskDto> = z.object({
  assigneeId: z.string().optional().describe(
    "ID of the user assigned to this risk",
  ),
  category: UpdateRiskDtoCategory$zodSchema.optional().describe(
    "Risk category",
  ),
  department: UpdateRiskDtoDepartment$zodSchema.optional().describe(
    "Department responsible for the risk",
  ),
  description: z.string().optional().describe(
    "Detailed description of the risk",
  ),
  impact: UpdateRiskDtoImpact$zodSchema.default("insignificant").describe(
    "Impact if the risk materializes",
  ),
  likelihood: UpdateRiskDtoLikelihood$zodSchema.default("very_unlikely")
    .describe("Likelihood of the risk occurring"),
  residualImpact: UpdateRiskDtoResidualImpact$zodSchema.default("insignificant")
    .describe("Residual impact after treatment"),
  residualLikelihood: UpdateRiskDtoResidualLikelihood$zodSchema.default(
    "very_unlikely",
  ).describe("Residual likelihood after treatment"),
  status: UpdateRiskDtoStatus$zodSchema.default("open").describe(
    "Current status of the risk",
  ),
  title: z.string().optional().describe("Risk title"),
  treatmentStrategy: UpdateRiskDtoTreatmentStrategy$zodSchema.default("accept")
    .describe("Risk treatment strategy"),
  treatmentStrategyDescription: z.string().optional().describe(
    "Description of the treatment strategy",
  ),
});
