/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateContextDto = {
  question?: string | undefined;
  answer?: string | undefined;
  tags?: Array<string> | undefined;
};

export const UpdateContextDto$zodSchema: z.ZodType<UpdateContextDto> = z.object(
  {
    answer: z.string().optional().describe(
      "The answer or detailed explanation for the question",
    ),
    question: z.string().optional().describe(
      "The question or topic this context entry addresses",
    ),
    tags: z.array(z.string()).optional().describe(
      "Tags to categorize and help search this context entry",
    ),
  },
);
