/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Obligations override for the built-in role.
 */
export type UpdateBuiltInObligationsDtoObligations = {
  compliance?: boolean | undefined;
};

export const UpdateBuiltInObligationsDtoObligations$zodSchema: z.ZodType<
  UpdateBuiltInObligationsDtoObligations
> = z.object({
  compliance: z.boolean().optional().describe(
    "Whether the role must complete compliance tasks.",
  ),
}).describe("Obligations override for the built-in role.");

export type UpdateBuiltInObligationsDto = {
  obligations: UpdateBuiltInObligationsDtoObligations;
};

export const UpdateBuiltInObligationsDto$zodSchema: z.ZodType<
  UpdateBuiltInObligationsDto
> = z.object({
  obligations: z.lazy(() => UpdateBuiltInObligationsDtoObligations$zodSchema)
    .describe("Obligations override for the built-in role."),
});
