/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EmailPreferencesDto,
  EmailPreferencesDto$zodSchema,
} from "./emailpreferencesdto.js";

export type UpdateEmailPreferencesDto = { preferences: EmailPreferencesDto };

export const UpdateEmailPreferencesDto$zodSchema: z.ZodType<
  UpdateEmailPreferencesDto
> = z.object({
  preferences: EmailPreferencesDto$zodSchema,
});
