/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UploadUrlResponseDto = {
  uploadUrl: string;
  s3Key: string;
  expiresIn: number;
};

export const UploadUrlResponseDto$zodSchema: z.ZodType<UploadUrlResponseDto> = z
  .object({
    expiresIn: z.number().describe("Seconds until the presigned URL expires."),
    s3Key: z.string().describe(
      "The S3 key the file will land at. Pass this to the feature endpoint (e.g. questionnaire upload-and-parse) instead of base64 file data.",
    ),
    uploadUrl: z.string().describe(
      "Presigned S3 URL. Send the raw file bytes with a plain HTTP PUT to this URL — no Content-Type or auth headers are required (the signature is in the URL). Then call the feature endpoint with the s3Key below.",
    ),
  });
