/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UploadAttachmentDto = {
  fileName: string;
  fileType: string;
  s3Key?: string | undefined;
  description?: string | undefined;
  userId?: string | undefined;
};

export const UploadAttachmentDto$zodSchema: z.ZodType<UploadAttachmentDto> = z
  .object({
    description: z.string().optional().describe(
      "Description of the attachment",
    ),
    fileName: z.string().describe("Name of the file"),
    fileType: z.string().describe("MIME type of the file"),
    s3Key: z.string().optional().describe(
      "Key of a file already uploaded via /v1/uploads/presign (purpose=attachment). The server fetches the bytes from storage — no base64 needed. Provide exactly one of fileData or s3Key.",
    ),
    userId: z.string().optional().describe(
      "User ID of the user uploading the attachment (required for API key auth, ignored for JWT auth)",
    ),
  });
