/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateUploadUrlDto,
  CreateUploadUrlDto$zodSchema,
} from "./createuploadurldto.js";

export type UploadsControllerCreateUploadUrlV1Request = {
  xOrganizationId?: string | undefined;
  body: CreateUploadUrlDto;
};

export const UploadsControllerCreateUploadUrlV1Request$zodSchema: z.ZodType<
  UploadsControllerCreateUploadUrlV1Request
> = z.object({
  body: CreateUploadUrlDto$zodSchema,
  xOrganizationId: z.string().describe(
    "Organization ID (required for session auth, optional for API key auth)",
  ).optional(),
});
