/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of entity this task item belongs to (vendor or risk)
 */
export const UploadTaskItemAttachmentDtoEntityType = {
  Vendor: "vendor",
  Risk: "risk",
} as const;
/**
 * Type of entity this task item belongs to (vendor or risk)
 */
export type UploadTaskItemAttachmentDtoEntityType = ClosedEnum<
  typeof UploadTaskItemAttachmentDtoEntityType
>;

export const UploadTaskItemAttachmentDtoEntityType$zodSchema = z.enum([
  "vendor",
  "risk",
]).describe("Type of entity this task item belongs to (vendor or risk)");

export type UploadTaskItemAttachmentDto = {
  fileName: string;
  fileType: string;
  fileData: string;
  entityType: UploadTaskItemAttachmentDtoEntityType;
  entityId: string;
};

export const UploadTaskItemAttachmentDto$zodSchema: z.ZodType<
  UploadTaskItemAttachmentDto
> = z.object({
  entityId: z.string().describe("ID of the entity this task item belongs to"),
  entityType: UploadTaskItemAttachmentDtoEntityType$zodSchema.describe(
    "Type of entity this task item belongs to (vendor or risk)",
  ),
  fileData: z.string().describe("Base64 encoded file data"),
  fileName: z.string().describe("Name of the file"),
  fileType: z.string().describe("MIME type of the file"),
});
