/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UploadTrustDocumentDto = {
  organizationId: string;
  fileName: string;
  fileType?: string | undefined;
  fileData: string;
  description?: string | undefined;
};

export const UploadTrustDocumentDto$zodSchema: z.ZodType<
  UploadTrustDocumentDto
> = z.object({
  description: z.string().optional().describe(
    "Optional description shown in the trust portal",
  ),
  fileData: z.string().describe(
    "Base64-encoded file contents (no data URL prefix)",
  ),
  fileName: z.string().describe("Original file name"),
  fileType: z.string().optional().describe("MIME type (optional)"),
  organizationId: z.string().describe("Organization ID that owns the document"),
});
