/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UploadAttachmentDto = {
  fileName: string;
  fileType: string;
  fileData: string;
  description?: string | undefined;
  userId?: string | undefined;
};

export const UploadAttachmentDto$zodSchema: z.ZodType<UploadAttachmentDto> = z
  .object({
    description: z.string().optional().describe(
      "Description of the attachment",
    ),
    fileData: z.string().describe("Base64 encoded file data"),
    fileName: z.string().describe("Name of the file"),
    fileType: z.string().describe("MIME type of the file"),
    userId: z.string().optional().describe(
      "User ID of the user uploading the attachment (required for API key auth, ignored for JWT auth)",
    ),
  });
