/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type VariablesControllerGetProviderVariablesV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const VariablesControllerGetProviderVariablesV1Security$zodSchema:
  z.ZodType<VariablesControllerGetProviderVariablesV1Security> = z.object({
    apikey: z.string().describe("API key for authentication").optional(),
    oauth2: z.string().describe(
      "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
    ).optional(),
  });

export type VariablesControllerGetProviderVariablesV1Request = {
  providerSlug: string;
};

export const VariablesControllerGetProviderVariablesV1Request$zodSchema:
  z.ZodType<VariablesControllerGetProviderVariablesV1Request> = z.object({
    providerSlug: z.string(),
  });
