/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export type VendorsControllerDeleteVendorV1Security = {
  apikey?: string | undefined;
  oauth2?: string | undefined;
};

export const VendorsControllerDeleteVendorV1Security$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1Security
> = z.object({
  apikey: z.string().describe("API key for authentication").optional(),
  oauth2: z.string().describe(
    "OAuth 2.1 authorization code flow. Sign in with your Comp AI account — tokens are issued by the Comp AI authorization server and scoped to your organization, role, and permissions.",
  ).optional(),
});

export type VendorsControllerDeleteVendorV1Request = { id: string };

export const VendorsControllerDeleteVendorV1Request$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1Request
> = z.object({
  id: z.string().describe("Vendor ID"),
});

/**
 * Internal server error
 */
export type VendorsControllerDeleteVendorV1InternalServerErrorResponseBody = {
  message?: string | undefined;
};

export const VendorsControllerDeleteVendorV1InternalServerErrorResponseBody$zodSchema:
  z.ZodType<VendorsControllerDeleteVendorV1InternalServerErrorResponseBody> = z
    .object({
      message: z.string().optional(),
    }).describe("Internal server error");

/**
 * Vendor not found
 */
export type VendorsControllerDeleteVendorV1NotFoundResponseBody = {
  message?: string | undefined;
};

export const VendorsControllerDeleteVendorV1NotFoundResponseBody$zodSchema:
  z.ZodType<VendorsControllerDeleteVendorV1NotFoundResponseBody> = z.object({
    message: z.string().optional(),
  }).describe("Vendor not found");

/**
 * Unauthorized - Invalid authentication or insufficient permissions
 */
export type VendorsControllerDeleteVendorV1UnauthorizedResponseBody = {
  message?: string | undefined;
};

export const VendorsControllerDeleteVendorV1UnauthorizedResponseBody$zodSchema:
  z.ZodType<VendorsControllerDeleteVendorV1UnauthorizedResponseBody> = z.object(
    {
      message: z.string().optional(),
    },
  ).describe(
    "Unauthorized - Invalid authentication or insufficient permissions",
  );

export type DeletedVendor = {
  id?: string | undefined;
  name?: string | undefined;
};

export const DeletedVendor$zodSchema: z.ZodType<DeletedVendor> = z.object({
  id: z.string().optional().describe("Deleted vendor ID"),
  name: z.string().optional().describe("Deleted vendor name"),
});

/**
 * How the request was authenticated
 */
export const VendorsControllerDeleteVendorV1AuthType = {
  ApiKey: "api-key",
  Session: "session",
} as const;
/**
 * How the request was authenticated
 */
export type VendorsControllerDeleteVendorV1AuthType = ClosedEnum<
  typeof VendorsControllerDeleteVendorV1AuthType
>;

export const VendorsControllerDeleteVendorV1AuthType$zodSchema = z.enum([
  "api-key",
  "session",
]).describe("How the request was authenticated");

/**
 * User information (only for session auth)
 */
export type VendorsControllerDeleteVendorV1AuthenticatedUser = {
  id?: string | undefined;
  email?: string | undefined;
};

export const VendorsControllerDeleteVendorV1AuthenticatedUser$zodSchema:
  z.ZodType<VendorsControllerDeleteVendorV1AuthenticatedUser> = z.object({
    email: z.string().optional(),
    id: z.string().optional(),
  }).describe("User information (only for session auth)");

/**
 * Vendor deleted successfully
 */
export type VendorsControllerDeleteVendorV1ResponseBody = {
  message?: string | undefined;
  deletedVendor?: DeletedVendor | undefined;
  authType?: VendorsControllerDeleteVendorV1AuthType | undefined;
  authenticatedUser?:
    | VendorsControllerDeleteVendorV1AuthenticatedUser
    | undefined;
};

export const VendorsControllerDeleteVendorV1ResponseBody$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1ResponseBody
> = z.object({
  authType: VendorsControllerDeleteVendorV1AuthType$zodSchema.optional()
    .describe("How the request was authenticated"),
  authenticatedUser: z.lazy(() =>
    VendorsControllerDeleteVendorV1AuthenticatedUser$zodSchema
  ).optional().describe("User information (only for session auth)"),
  deletedVendor: z.lazy(() => DeletedVendor$zodSchema).optional(),
  message: z.string().optional(),
}).describe("Vendor deleted successfully");

export type VendorsControllerDeleteVendorV1Response =
  | VendorsControllerDeleteVendorV1ResponseBody
  | VendorsControllerDeleteVendorV1UnauthorizedResponseBody
  | VendorsControllerDeleteVendorV1NotFoundResponseBody
  | VendorsControllerDeleteVendorV1InternalServerErrorResponseBody;

export const VendorsControllerDeleteVendorV1Response$zodSchema: z.ZodType<
  VendorsControllerDeleteVendorV1Response
> = z.union([
  z.lazy(() => VendorsControllerDeleteVendorV1ResponseBody$zodSchema),
  z.lazy(() =>
    VendorsControllerDeleteVendorV1UnauthorizedResponseBody$zodSchema
  ),
  z.lazy(() => VendorsControllerDeleteVendorV1NotFoundResponseBody$zodSchema),
  z.lazy(() =>
    VendorsControllerDeleteVendorV1InternalServerErrorResponseBody$zodSchema
  ),
]);
