/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerDetectGcpOrgV1 } from "../../funcs/cloudSecurityCloudSecurityControllerDetectGcpOrgV1.js";
import { CloudSecurityControllerDetectGcpOrgV1Request$zodSchema } from "../../models/cloudsecuritycontrollerdetectgcporgv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerDetectGcpOrgV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerDetectGcpOrgV1:
  ToolDefinition<typeof args> = {
    name: "detect-gcp-org",
    description: `Detect the GCP organization for a connection

Detect the GCP organization for a connection in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await cloudSecurityCloudSecurityControllerDetectGcpOrgV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
