/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1 } from "../../funcs/cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1.js";
import { CloudSecurityControllerResolveGcpSetupStepV1Request$zodSchema } from "../../models/cloudsecuritycontrollerresolvegcpsetupstepv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerResolveGcpSetupStepV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1:
  ToolDefinition<typeof args> = {
    name: "resolve-gcp-setup-step",
    description: `Resolve a GCP setup step

Resolve a GCP setup step in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await cloudSecurityCloudSecurityControllerResolveGcpSetupStepV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
