/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerDetectServicesV1 } from "../../funcs/cloudSecurityCloudSecurityControllerDetectServicesV1.js";
import { CloudSecurityControllerDetectServicesV1Request$zodSchema } from "../../models/cloudsecuritycontrollerdetectservicesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerDetectServicesV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerDetectServicesV1:
  ToolDefinition<typeof args> = {
    name: "detect-services",
    description: `Detect available cloud services for a connection

Detect available cloud services for a connection in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await cloudSecurityCloudSecurityControllerDetectServicesV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
