/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerGetHistoryV1 } from "../../funcs/cloudSecurityCloudSecurityControllerGetHistoryV1.js";
import { CloudSecurityControllerGetHistoryV1Request$zodSchema } from "../../models/cloudsecuritycontrollergethistoryv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerGetHistoryV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerGetHistoryV1:
  ToolDefinition<typeof args> = {
    name: "get-history",
    description:
      `List resolution, exception, and regression history for a connection

List resolution, exception, and regression history for a connection in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await cloudSecurityCloudSecurityControllerGetHistoryV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
