/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerSetupGcpV1 } from "../../funcs/cloudSecurityCloudSecurityControllerSetupGcpV1.js";
import { CloudSecurityControllerSetupGcpV1Request$zodSchema } from "../../models/cloudsecuritycontrollersetupgcpv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerSetupGcpV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerSetupGcpV1:
  ToolDefinition<typeof args> = {
    name: "setup-gcp",
    description: `Set up GCP for a connection

Set up GCP for a connection in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await cloudSecurityCloudSecurityControllerSetupGcpV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
