/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cloudSecurityCloudSecurityControllerSelectGcpProjectsV1 } from "../../funcs/cloudSecurityCloudSecurityControllerSelectGcpProjectsV1.js";
import { CloudSecurityControllerSelectGcpProjectsV1Request$zodSchema } from "../../models/cloudsecuritycontrollerselectgcpprojectsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CloudSecurityControllerSelectGcpProjectsV1Request$zodSchema,
};

export const tool$cloudSecurityCloudSecurityControllerSelectGcpProjectsV1:
  ToolDefinition<typeof args> = {
    name: "select-gcp-projects",
    description: `Select GCP projects for a connection

Select GCP projects for a connection in Comp AI. Run AWS, Azure, and GCP cloud security scans, detect enabled services, review findings, and connect cloud posture results to compliance work.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await cloudSecurityCloudSecurityControllerSelectGcpProjectsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
