/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contextContextControllerGetContextByIdV1 } from "../../funcs/contextContextControllerGetContextByIdV1.js";
import { ContextControllerGetContextByIdV1Request$zodSchema } from "../../models/contextcontrollergetcontextbyidv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ContextControllerGetContextByIdV1Request$zodSchema,
};

export const tool$contextContextControllerGetContextByIdV1: ToolDefinition<
  typeof args
> = {
  name: "get-context-by-id",
  description: `Get organization context

Retrieve one organization context entry with source details and approved content for compliance automation workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await contextContextControllerGetContextByIdV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
