/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deviceAgentDeviceAgentControllerCheckInV1 } from "../../funcs/deviceAgentDeviceAgentControllerCheckInV1.js";
import { CheckInDto$zodSchema } from "../../models/checkindto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CheckInDto$zodSchema,
};

export const tool$deviceAgentDeviceAgentControllerCheckInV1: ToolDefinition<
  typeof args
> = {
  name: "check-in",
  description: `Submit device compliance check-in

Submit device security check results for encryption, antivirus, password policy, screen lock, and other endpoint controls.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await deviceAgentDeviceAgentControllerCheckInV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
