/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deviceAgentDeviceAgentControllerRevokeAgentAccessV1 } from "../../funcs/deviceAgentDeviceAgentControllerRevokeAgentAccessV1.js";
import { DeviceAgentControllerRevokeAgentAccessV1Request$zodSchema } from "../../models/deviceagentcontrollerrevokeagentaccessv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeviceAgentControllerRevokeAgentAccessV1Request$zodSchema,
};

export const tool$deviceAgentDeviceAgentControllerRevokeAgentAccessV1:
  ToolDefinition<typeof args> = {
    name: "revoke-agent-access",
    description: `Revoke a device agent session

Revoke a device agent session in Comp AI. Register employee devices, submit device compliance check-ins, download agent builds, and manage endpoint security status.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await deviceAgentDeviceAgentControllerRevokeAgentAccessV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
