/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deviceAgentDeviceAgentControllerRegisterDeviceV1 } from "../../funcs/deviceAgentDeviceAgentControllerRegisterDeviceV1.js";
import { RegisterDeviceDto$zodSchema } from "../../models/registerdevicedto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RegisterDeviceDto$zodSchema,
};

export const tool$deviceAgentDeviceAgentControllerRegisterDeviceV1:
  ToolDefinition<typeof args> = {
    name: "register-device",
    description: `Register device agent

Register a Comp AI Device Agent installation so employee endpoint checks can report into compliance tasks and device inventory.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await deviceAgentDeviceAgentControllerRegisterDeviceV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
