/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceExportEvidenceExportControllerExportAutomationPDFV1 } from "../../funcs/evidenceExportEvidenceExportControllerExportAutomationPDFV1.js";
import { EvidenceExportControllerExportAutomationPdfv1Request$zodSchema } from "../../models/evidenceexportcontrollerexportautomationpdfv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EvidenceExportControllerExportAutomationPdfv1Request$zodSchema,
};

export const tool$evidenceExportEvidenceExportControllerExportAutomationPDFV1:
  ToolDefinition<typeof args> = {
    name: "export-automation-pdf",
    description: `Export automation evidence as PDF

Export automation evidence as PDF in Comp AI. Export task evidence, automation evidence, and reviewer-ready evidence bundles as PDF or ZIP files.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceExportEvidenceExportControllerExportAutomationPDFV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
