/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1 } from "../../funcs/evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1.js";
import { EvidenceExportControllerGetTaskEvidenceSummaryV1Request$zodSchema } from "../../models/evidenceexportcontrollergettaskevidencesummaryv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EvidenceExportControllerGetTaskEvidenceSummaryV1Request$zodSchema,
};

export const tool$evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1:
  ToolDefinition<typeof args> = {
    name: "get-task-evidence-summary",
    description: `Get task evidence summary

Get task evidence summary in Comp AI. Export task evidence, automation evidence, and reviewer-ready evidence bundles as PDF or ZIP files.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceExportEvidenceExportControllerGetTaskEvidenceSummaryV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
