/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1 } from "../../funcs/evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1.js";
import { AuditorEvidenceExportControllerExportAllEvidenceV1Request$zodSchema } from "../../models/auditorevidenceexportcontrollerexportallevidencev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AuditorEvidenceExportControllerExportAllEvidenceV1Request$zodSchema
    .optional(),
};

export const tool$evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1:
  ToolDefinition<typeof args> = {
    name: "export-all-evidence",
    description: `Trigger bulk evidence export (Auditor only)

Trigger bulk evidence export (Auditor only) in Comp AI. Export all organization evidence for an auditor review package.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceExportAuditorAuditorEvidenceExportControllerExportAllEvidenceV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
