/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1 } from "../../funcs/evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1.js";
import { EvidenceExportControllerExportTaskEvidenceZipV1Request$zodSchema } from "../../models/evidenceexportcontrollerexporttaskevidencezipv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EvidenceExportControllerExportTaskEvidenceZipV1Request$zodSchema,
};

export const tool$evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1:
  ToolDefinition<typeof args> = {
    name: "export-task-evidence-zip",
    description: `Export task evidence as ZIP

Download a ZIP package containing task evidence and automation results for auditor review or customer security requests.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceExportEvidenceExportControllerExportTaskEvidenceZipV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
