/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceFormsEvidenceFormsControllerGetMySubmissionsV1 } from "../../funcs/evidenceFormsEvidenceFormsControllerGetMySubmissionsV1.js";
import { EvidenceFormsControllerGetMySubmissionsV1Request$zodSchema } from "../../models/evidenceformscontrollergetmysubmissionsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EvidenceFormsControllerGetMySubmissionsV1Request$zodSchema,
};

export const tool$evidenceFormsEvidenceFormsControllerGetMySubmissionsV1:
  ToolDefinition<typeof args> = {
    name: "get-my-submissions",
    description: `Get current user submissions

Get current user submissions in Comp AI. Collect, review, upload, and export structured evidence submissions for compliance tasks and document requirements.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceFormsEvidenceFormsControllerGetMySubmissionsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
