/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evidenceFormsEvidenceFormsControllerUploadSubmissionV1 } from "../../funcs/evidenceFormsEvidenceFormsControllerUploadSubmissionV1.js";
import { EvidenceFormsControllerUploadSubmissionV1Request$zodSchema } from "../../models/evidenceformscontrolleruploadsubmissionv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EvidenceFormsControllerUploadSubmissionV1Request$zodSchema,
};

export const tool$evidenceFormsEvidenceFormsControllerUploadSubmissionV1:
  ToolDefinition<typeof args> = {
    name: "upload-submission",
    description: `Upload a file as an evidence submission

Upload a PDF or image file and create a submission for the given form type, bypassing form-specific validation. Accepts session, API key, or service token auth. For API key / service token callers without an explicit user attribution, the.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await evidenceFormsEvidenceFormsControllerUploadSubmissionV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
