/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { findingsFindingsControllerGetFindingByIdV1 } from "../../funcs/findingsFindingsControllerGetFindingByIdV1.js";
import { FindingsControllerGetFindingByIdV1Request$zodSchema } from "../../models/findingscontrollergetfindingbyidv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FindingsControllerGetFindingByIdV1Request$zodSchema,
};

export const tool$findingsFindingsControllerGetFindingByIdV1: ToolDefinition<
  typeof args
> = {
  name: "get-finding-by-id",
  description: `Get finding by ID

Get finding by ID in Comp AI. Create, review, update, and track audit findings, remediation activity, and finding history for an organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await findingsFindingsControllerGetFindingByIdV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
