/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsSyncControllerSetEmployeeSyncProviderV1 } from "../../funcs/integrationsSyncControllerSetEmployeeSyncProviderV1.js";
import { SetEmployeeSyncProviderDto$zodSchema } from "../../models/setemployeesyncproviderdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SetEmployeeSyncProviderDto$zodSchema,
};

export const tool$integrationsSyncControllerSetEmployeeSyncProviderV1:
  ToolDefinition<typeof args> = {
    name: "set-employee-sync-provider",
    description: `Set the employee sync provider

Set the employee sync provider in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await integrationsSyncControllerSetEmployeeSyncProviderV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
