/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsSyncControllerSyncDynamicProviderEmployeesV1 } from "../../funcs/integrationsSyncControllerSyncDynamicProviderEmployeesV1.js";
import { SyncControllerSyncDynamicProviderEmployeesV1Request$zodSchema } from "../../models/synccontrollersyncdynamicprovideremployeesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SyncControllerSyncDynamicProviderEmployeesV1Request$zodSchema,
};

export const tool$integrationsSyncControllerSyncDynamicProviderEmployeesV1:
  ToolDefinition<typeof args> = {
    name: "sync-dynamic-provider-employees",
    description: `Sync employees for a dynamic provider

Sync employees for a dynamic provider in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await integrationsSyncControllerSyncDynamicProviderEmployeesV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
