/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsChecksControllerListProviderChecksV1 } from "../../funcs/integrationsChecksControllerListProviderChecksV1.js";
import { ChecksControllerListProviderChecksV1Request$zodSchema } from "../../models/checkscontrollerlistproviderchecksv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ChecksControllerListProviderChecksV1Request$zodSchema,
};

export const tool$integrationsChecksControllerListProviderChecksV1:
  ToolDefinition<typeof args> = {
    name: "list-provider-checks",
    description: `List check definitions for a provider

List check definitions for a provider in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await integrationsChecksControllerListProviderChecksV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
