/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsConnectionsControllerTestConnectionV1 } from "../../funcs/integrationsConnectionsControllerTestConnectionV1.js";
import { ConnectionsControllerTestConnectionV1Request$zodSchema } from "../../models/connectionscontrollertestconnectionv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ConnectionsControllerTestConnectionV1Request$zodSchema,
};

export const tool$integrationsConnectionsControllerTestConnectionV1:
  ToolDefinition<typeof args> = {
    name: "test-connection",
    description: `Test an integration connection

Test an integration connection in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await integrationsConnectionsControllerTestConnectionV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
