/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsConnectionsControllerUpdateConnectionServicesV1 } from "../../funcs/integrationsConnectionsControllerUpdateConnectionServicesV1.js";
import { ConnectionsControllerUpdateConnectionServicesV1Request$zodSchema } from "../../models/connectionscontrollerupdateconnectionservicesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ConnectionsControllerUpdateConnectionServicesV1Request$zodSchema,
};

export const tool$integrationsConnectionsControllerUpdateConnectionServicesV1:
  ToolDefinition<typeof args> = {
    name: "update-connection-services",
    description: `Set services enabled on a connection

Set services enabled on a connection in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await integrationsConnectionsControllerUpdateConnectionServicesV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
