/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsTaskIntegrationsControllerGetChecksForTaskV1 } from "../../funcs/integrationsTaskIntegrationsControllerGetChecksForTaskV1.js";
import { TaskIntegrationsControllerGetChecksForTaskV1Request$zodSchema } from "../../models/taskintegrationscontrollergetchecksfortaskv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TaskIntegrationsControllerGetChecksForTaskV1Request$zodSchema,
};

export const tool$integrationsTaskIntegrationsControllerGetChecksForTaskV1:
  ToolDefinition<typeof args> = {
    name: "get-checks-for-task",
    description: `List checks attached to a task

List checks attached to a task in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await integrationsTaskIntegrationsControllerGetChecksForTaskV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
