/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsChecksControllerRunConnectionChecksV1 } from "../../funcs/integrationsChecksControllerRunConnectionChecksV1.js";
import { ChecksControllerRunConnectionChecksV1Request$zodSchema } from "../../models/checkscontrollerrunconnectionchecksv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ChecksControllerRunConnectionChecksV1Request$zodSchema,
};

export const tool$integrationsChecksControllerRunConnectionChecksV1:
  ToolDefinition<typeof args> = {
    name: "run-connection-checks",
    description: `Run integration checks

Run all compliance checks for an integration connection and capture results as automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await integrationsChecksControllerRunConnectionChecksV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
