/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsConnectionsControllerGetProviderV1 } from "../../funcs/integrationsConnectionsControllerGetProviderV1.js";
import { ConnectionsControllerGetProviderV1Request$zodSchema } from "../../models/connectionscontrollergetproviderv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ConnectionsControllerGetProviderV1Request$zodSchema,
};

export const tool$integrationsConnectionsControllerGetProviderV1:
  ToolDefinition<typeof args> = {
    name: "get-provider",
    description: `Get an integration provider by slug

Get an integration provider by slug in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await integrationsConnectionsControllerGetProviderV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
