/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsVariablesControllerSaveConnectionVariablesV1 } from "../../funcs/integrationsVariablesControllerSaveConnectionVariablesV1.js";
import { VariablesControllerSaveConnectionVariablesV1Request$zodSchema } from "../../models/variablescontrollersaveconnectionvariablesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VariablesControllerSaveConnectionVariablesV1Request$zodSchema,
};

export const tool$integrationsVariablesControllerSaveConnectionVariablesV1:
  ToolDefinition<typeof args> = {
    name: "save-connection-variables",
    description: `Update connection variables

Update connection variables in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await integrationsVariablesControllerSaveConnectionVariablesV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
