/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsSyncControllerGetRipplingStatusV1 } from "../../funcs/integrationsSyncControllerGetRipplingStatusV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$integrationsSyncControllerGetRipplingStatusV1:
  ToolDefinition = {
    name: "get-rippling-status",
    description: `Get Rippling sync status

Get Rippling sync status in Comp AI. Connect vendor systems, configure OAuth apps, run compliance checks, sync employees, manage variables, and collect automated evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] = await integrationsSyncControllerGetRipplingStatusV1(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
