/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ismsISMSControllerRemoveControlV1 } from "../../funcs/ismsISMSControllerRemoveControlV1.js";
import { IsmsControllerRemoveControlV1Request$zodSchema } from "../../models/ismscontrollerremovecontrolv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IsmsControllerRemoveControlV1Request$zodSchema,
};

export const tool$ismsISMSControllerRemoveControlV1: ToolDefinition<
  typeof args
> = {
  name: "remove-control",
  description: `Remove a control mapping from an ISMS document

Remove a control mapping from an ISMS document in Comp AI.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ismsISMSControllerRemoveControlV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
