/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1 } from "../../funcs/knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1.js";
import { KnowledgeBaseControllerDeleteDocumentV1Request$zodSchema } from "../../models/knowledgebasecontrollerdeletedocumentv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: KnowledgeBaseControllerDeleteDocumentV1Request$zodSchema,
};

export const tool$knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1:
  ToolDefinition<typeof args> = {
    name: "delete-document",
    description: `Delete a knowledge base document

Delete a knowledge base document in Comp AI. Upload source documents, process them for retrieval, and manage reusable manual answers that power questionnaires and AI policy workflows.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await knowledgeBaseKnowledgeBaseControllerDeleteDocumentV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
