/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1 } from "../../funcs/knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1.js";
import { ProcessDocumentsDto$zodSchema } from "../../models/processdocumentsdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ProcessDocumentsDto$zodSchema,
};

export const tool$knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1:
  ToolDefinition<typeof args> = {
    name: "process-documents",
    description: `Process knowledge base documents

Start document processing so uploaded knowledge base files become searchable source material for AI-assisted compliance workflows.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await knowledgeBaseKnowledgeBaseControllerProcessDocumentsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
