/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1 } from "../../funcs/knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1.js";
import { KnowledgeBaseControllerDeleteManualAnswerV1Request$zodSchema } from "../../models/knowledgebasecontrollerdeletemanualanswerv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: KnowledgeBaseControllerDeleteManualAnswerV1Request$zodSchema,
};

export const tool$knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1:
  ToolDefinition<typeof args> = {
    name: "delete-manual-answer",
    description: `Delete a manual answer

Delete a manual answer in Comp AI. Upload source documents, process them for retrieval, and manage reusable manual answers that power questionnaires and AI policy workflows.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await knowledgeBaseKnowledgeBaseControllerDeleteManualAnswerV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
