/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1 } from "../../funcs/offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1.js";
import { OffboardingChecklistControllerGetMemberChecklistV1Request$zodSchema } from "../../models/offboardingchecklistcontrollergetmemberchecklistv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OffboardingChecklistControllerGetMemberChecklistV1Request$zodSchema,
};

export const tool$offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1:
  ToolDefinition<typeof args> = {
    name: "get-member-checklist",
    description: `Get a member's offboarding checklist

Returns the offboarding checklist for a specific member, including each item and whether it has been completed, to track that person's offboarding progress.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await offboardingChecklistOffboardingChecklistControllerGetMemberChecklistV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
