/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1 } from "../../funcs/offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1:
  ToolDefinition = {
    name: "get-pending-offboardings",
    description: `Get members with pending offboarding checklists

Lists members whose offboarding checklist is still incomplete, with their outstanding items, so you can track and finish departing-employee offboarding.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] =
        await offboardingChecklistOffboardingChecklistControllerGetPendingOffboardingsV1(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
