/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1 } from "../../funcs/offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1.js";
import { OffboardingChecklistControllerRevokeAllVendorAccessV1Request$zodSchema } from "../../models/offboardingchecklistcontrollerrevokeallvendoraccessv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    OffboardingChecklistControllerRevokeAllVendorAccessV1Request$zodSchema,
};

export const tool$offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1:
  ToolDefinition<typeof args> = {
    name: "revoke-all-vendor-access",
    description: `Confirm all vendor access as revoked

Confirm all vendor access as revoked in Comp AI.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await offboardingChecklistOffboardingChecklistControllerRevokeAllVendorAccessV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
