/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { offboardingChecklistOffboardingChecklistControllerExportEvidenceV1 } from "../../funcs/offboardingChecklistOffboardingChecklistControllerExportEvidenceV1.js";
import { OffboardingChecklistControllerExportEvidenceV1Request$zodSchema } from "../../models/offboardingchecklistcontrollerexportevidencev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OffboardingChecklistControllerExportEvidenceV1Request$zodSchema,
};

export const tool$offboardingChecklistOffboardingChecklistControllerExportEvidenceV1:
  ToolDefinition<typeof args> = {
    name: "export-evidence",
    description: `Export offboarding evidence as a zip file

Export offboarding evidence as a zip file in Comp AI.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await offboardingChecklistOffboardingChecklistControllerExportEvidenceV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
