/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1 } from "../../funcs/offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1.js";
import { CreateTemplateItemDto$zodSchema } from "../../models/createtemplateitemdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateTemplateItemDto$zodSchema,
};

export const tool$offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1:
  ToolDefinition<typeof args> = {
    name: "create-template-item",
    description: ``,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await offboardingChecklistOffboardingChecklistControllerCreateTemplateItemV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
