/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationOrganizationControllerUpdateOrganizationV1 } from "../../funcs/organizationOrganizationControllerUpdateOrganizationV1.js";
import { OrganizationControllerUpdateOrganizationV1Request$zodSchema } from "../../models/organizationcontrollerupdateorganizationv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OrganizationControllerUpdateOrganizationV1Request$zodSchema.describe(
    `Organization update data`,
  ),
};

export const tool$organizationOrganizationControllerUpdateOrganizationV1:
  ToolDefinition<typeof args> = {
    name: "update-organization",
    description: `Update organization

Partially updates the authenticated organization. Only provided fields will be updated.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await organizationOrganizationControllerUpdateOrganizationV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
