/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peoplePeopleControllerUnlinkDeviceV1 } from "../../funcs/peoplePeopleControllerUnlinkDeviceV1.js";
import { PeopleControllerUnlinkDeviceV1Request$zodSchema } from "../../models/peoplecontrollerunlinkdevicev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PeopleControllerUnlinkDeviceV1Request$zodSchema,
};

export const tool$peoplePeopleControllerUnlinkDeviceV1: ToolDefinition<
  typeof args
> = {
  name: "unlink-device",
  description: `Unlink device from member

Resets the fleetDmLabelId for a member, effectively unlinking their device from FleetDM. This will disconnect the device from the organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await peoplePeopleControllerUnlinkDeviceV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
