/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peoplePeopleControllerGetPersonByIdV1 } from "../../funcs/peoplePeopleControllerGetPersonByIdV1.js";
import { PeopleControllerGetPersonByIdV1Request$zodSchema } from "../../models/peoplecontrollergetpersonbyidv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PeopleControllerGetPersonByIdV1Request$zodSchema,
};

export const tool$peoplePeopleControllerGetPersonByIdV1: ToolDefinition<
  typeof args
> = {
  name: "get-member",
  description: `Get person by ID

Returns a specific member by ID for the authenticated organization with their user information.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await peoplePeopleControllerGetPersonByIdV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
