/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peoplePeopleControllerInviteMembersV1 } from "../../funcs/peoplePeopleControllerInviteMembersV1.js";
import { InvitePeopleDto$zodSchema } from "../../models/invitepeopledto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InvitePeopleDto$zodSchema,
};

export const tool$peoplePeopleControllerInviteMembersV1: ToolDefinition<
  typeof args
> = {
  name: "invite-members",
  description: `Invite workforce members

Invite employees or contractors to complete portal tasks, training, device setup, and compliance evidence requirements.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await peoplePeopleControllerInviteMembersV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
