/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peoplePeopleControllerGetMentionableMembersV1 } from "../../funcs/peoplePeopleControllerGetMentionableMembersV1.js";
import { PeopleControllerGetMentionableMembersV1Request$zodSchema } from "../../models/peoplecontrollergetmentionablemembersv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PeopleControllerGetMentionableMembersV1Request$zodSchema,
};

export const tool$peoplePeopleControllerGetMentionableMembersV1: ToolDefinition<
  typeof args
> = {
  name: "get-mentionable-members",
  description: `Get members who can read a specific resource type

Get members who can read a specific resource type in Comp AI. Invite and manage workforce members, training status, device compliance, email preferences, and employee evidence records.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await peoplePeopleControllerGetMentionableMembersV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
