/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { peoplePeopleControllerGetAllPeopleV1 } from "../../funcs/peoplePeopleControllerGetAllPeopleV1.js";
import { PeopleControllerGetAllPeopleV1Request$zodSchema } from "../../models/peoplecontrollergetallpeoplev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PeopleControllerGetAllPeopleV1Request$zodSchema,
};

export const tool$peoplePeopleControllerGetAllPeopleV1: ToolDefinition<
  typeof args
> = {
  name: "list-members",
  description: `List workforce members

List employees and contractors with onboarding, training, device, and compliance status used for people-security controls.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await peoplePeopleControllerGetAllPeopleV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
