/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerDownloadAllPoliciesV1 } from "../../funcs/policiesPoliciesControllerDownloadAllPoliciesV1.js";
import { PoliciesControllerDownloadAllPoliciesV1Request$zodSchema } from "../../models/policiescontrollerdownloadallpoliciesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerDownloadAllPoliciesV1Request$zodSchema.optional(),
};

export const tool$policiesPoliciesControllerDownloadAllPoliciesV1:
  ToolDefinition<typeof args> = {
    name: "download-all-policies",
    description: `Download all published policies

Generate a single PDF bundle of published compliance policies for auditors, customer security reviews, and Trust Center workflows.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await policiesPoliciesControllerDownloadAllPoliciesV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
