/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerGetPolicyControlsV1 } from "../../funcs/policiesPoliciesControllerGetPolicyControlsV1.js";
import { PoliciesControllerGetPolicyControlsV1Request$zodSchema } from "../../models/policiescontrollergetpolicycontrolsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerGetPolicyControlsV1Request$zodSchema,
};

export const tool$policiesPoliciesControllerGetPolicyControlsV1: ToolDefinition<
  typeof args
> = {
  name: "get-policy-controls",
  description: `Get mapped and all controls for a policy

Get mapped and all controls for a policy in Comp AI. Create, version, publish, export, map, and improve compliance policies with AI-assisted drafting and approval workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await policiesPoliciesControllerGetPolicyControlsV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
