/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerConfirmPolicyPdfUploadedV1 } from "../../funcs/policiesPoliciesControllerConfirmPolicyPdfUploadedV1.js";
import { PoliciesControllerConfirmPolicyPdfUploadedV1Request$zodSchema } from "../../models/policiescontrollerconfirmpolicypdfuploadedv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerConfirmPolicyPdfUploadedV1Request$zodSchema,
};

export const tool$policiesPoliciesControllerConfirmPolicyPdfUploadedV1:
  ToolDefinition<typeof args> = {
    name: "confirm-policy-pdf-uploaded",
    description: `Confirm a policy PDF upload completed

Links an uploaded PDF to a compliance policy after the file has been PUT to a presigned S3 URL. Call this after request-policy-pdf-upload-url returned an s3Key and you successfully uploaded the file bytes to that URL. The endpoint verifies the file exists in S3 before linking it to the policy or version.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await policiesPoliciesControllerConfirmPolicyPdfUploadedV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
