/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerRequestPolicyPdfUploadUrlV1 } from "../../funcs/policiesPoliciesControllerRequestPolicyPdfUploadUrlV1.js";
import { PoliciesControllerRequestPolicyPdfUploadUrlV1Request$zodSchema } from "../../models/policiescontrollerrequestpolicypdfuploadurlv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerRequestPolicyPdfUploadUrlV1Request$zodSchema,
};

export const tool$policiesPoliciesControllerRequestPolicyPdfUploadUrlV1:
  ToolDefinition<typeof args> = {
    name: "request-policy-pdf-upload-url",
    description: `Request a presigned URL to upload a policy PDF

Generates a presigned S3 URL for uploading a policy PDF directly to storage. Use this when attaching a PDF to a compliance policy — the file bytes are uploaded straight to S3 without passing through the API. Requires the policy ID; if you only know the policy name, look it up first via the list-compliance-policies tool. After uploading the file to the returned URL, finalize the attachment by calling confirm-policy-pdf-uploaded with the same s3Key.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await policiesPoliciesControllerRequestPolicyPdfUploadUrlV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
