/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerDeletePolicyPdfV1 } from "../../funcs/policiesPoliciesControllerDeletePolicyPdfV1.js";
import { PoliciesControllerDeletePolicyPdfV1Request$zodSchema } from "../../models/policiescontrollerdeletepolicypdfv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerDeletePolicyPdfV1Request$zodSchema,
};

export const tool$policiesPoliciesControllerDeletePolicyPdfV1: ToolDefinition<
  typeof args
> = {
  name: "delete-policy-pdf",
  description: `Delete a policy version PDF

Deletes the PDF from a specific policy version. If no versionId is provided, deletes from the latest draft version. Cannot delete PDFs from published or pending-approval versions.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await policiesPoliciesControllerDeletePolicyPdfV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
