/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerGetAllPoliciesV1 } from "../../funcs/policiesPoliciesControllerGetAllPoliciesV1.js";
import { PoliciesControllerGetAllPoliciesV1Request$zodSchema } from "../../models/policiescontrollergetallpoliciesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerGetAllPoliciesV1Request$zodSchema.optional(),
};

export const tool$policiesPoliciesControllerGetAllPoliciesV1: ToolDefinition<
  typeof args
> = {
  name: "list-policies",
  description: `List compliance policies

Lists active compliance policies by default. Use includeArchived=true to include archived rows and excludeContent=true when you only need policy metadata.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await policiesPoliciesControllerGetAllPoliciesV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
