/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { policiesPoliciesControllerPublishAllPoliciesV1 } from "../../funcs/policiesPoliciesControllerPublishAllPoliciesV1.js";
import { PoliciesControllerPublishAllPoliciesV1Request$zodSchema } from "../../models/policiescontrollerpublishallpoliciesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PoliciesControllerPublishAllPoliciesV1Request$zodSchema.optional(),
};

export const tool$policiesPoliciesControllerPublishAllPoliciesV1:
  ToolDefinition<typeof args> = {
    name: "publish-all-policies",
    description: `Publish all draft policies

Publish draft policies in bulk so approved policy content can power Trust Center sharing, questionnaire answers, and audit evidence.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await policiesPoliciesControllerPublishAllPoliciesV1(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
