/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { risksRisksControllerDeleteRiskV1 } from "../../funcs/risksRisksControllerDeleteRiskV1.js";
import { RisksControllerDeleteRiskV1Request$zodSchema } from "../../models/riskscontrollerdeleteriskv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RisksControllerDeleteRiskV1Request$zodSchema,
};

export const tool$risksRisksControllerDeleteRiskV1: ToolDefinition<
  typeof args
> = {
  name: "delete-risk",
  description: `Delete organization risk

Delete an organization risk that no longer needs active tracking in the risk register or compliance program.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await risksRisksControllerDeleteRiskV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
