/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rolesRolesControllerGetRoleV1 } from "../../funcs/rolesRolesControllerGetRoleV1.js";
import { RolesControllerGetRoleV1Request$zodSchema } from "../../models/rolescontrollergetrolev1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RolesControllerGetRoleV1Request$zodSchema,
};

export const tool$rolesRolesControllerGetRoleV1: ToolDefinition<typeof args> = {
  name: "get-role",
  description: `Get a role by ID

Get a role by ID in Comp AI. Create custom roles and resolve permission sets for organization-level access control.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await rolesRolesControllerGetRoleV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
