/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rolesRolesControllerGetPermissionsForRolesV1 } from "../../funcs/rolesRolesControllerGetPermissionsForRolesV1.js";
import { RolesControllerGetPermissionsForRolesV1Request$zodSchema } from "../../models/rolescontrollergetpermissionsforrolesv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RolesControllerGetPermissionsForRolesV1Request$zodSchema,
};

export const tool$rolesRolesControllerGetPermissionsForRolesV1: ToolDefinition<
  typeof args
> = {
  name: "get-permissions-for-roles",
  description: `Resolve permissions for custom roles

Returns the merged permissions for the given custom role names. Used by the frontend to resolve effective permissions for users with custom roles.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await rolesRolesControllerGetPermissionsForRolesV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
