/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1 } from "../../funcs/securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1.js";
import { SecurityPenetrationTestsControllerGetEventsV1Request$zodSchema } from "../../models/securitypenetrationtestscontrollergeteventsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SecurityPenetrationTestsControllerGetEventsV1Request$zodSchema,
};

export const tool$securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1:
  ToolDefinition<typeof args> = {
    name: "get-events",
    description: `Get penetration test agent events

Returns the real-time agent activity log emitted during a run (tool calls, observations, etc.). Noisy — meant for activity feeds and debugging.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await securityPenetrationTestsSecurityPenetrationTestsControllerGetEventsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
