/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksTasksControllerCreateTaskV1 } from "../../funcs/tasksTasksControllerCreateTaskV1.js";
import { TasksControllerCreateTaskV1Request$zodSchema } from "../../models/taskscontrollercreatetaskv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TasksControllerCreateTaskV1Request$zodSchema,
};

export const tool$tasksTasksControllerCreateTaskV1: ToolDefinition<
  typeof args
> = {
  name: "create-task",
  description: `Create compliance task

Create a compliance task for evidence collection, remediation, review, or recurring control work inside an organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await tasksTasksControllerCreateTaskV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
