/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskAutomationsAutomationsControllerGetAutomationVersionsV1 } from "../../funcs/taskAutomationsAutomationsControllerGetAutomationVersionsV1.js";
import { AutomationsControllerGetAutomationVersionsV1Request$zodSchema } from "../../models/automationscontrollergetautomationversionsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AutomationsControllerGetAutomationVersionsV1Request$zodSchema,
};

export const tool$taskAutomationsAutomationsControllerGetAutomationVersionsV1:
  ToolDefinition<typeof args> = {
    name: "get-automation-versions",
    description: `Get all versions for an automation

Get all versions for an automation in Comp AI. Create, version, run, and inspect automated evidence collection workflows attached to compliance tasks.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await taskAutomationsAutomationsControllerGetAutomationVersionsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
