/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskAutomationsAutomationsControllerCreateAutomationV1 } from "../../funcs/taskAutomationsAutomationsControllerCreateAutomationV1.js";
import { AutomationsControllerCreateAutomationV1Request$zodSchema } from "../../models/automationscontrollercreateautomationv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AutomationsControllerCreateAutomationV1Request$zodSchema,
};

export const tool$taskAutomationsAutomationsControllerCreateAutomationV1:
  ToolDefinition<typeof args> = {
    name: "create-automation",
    description: `Create evidence automation

Create an automated evidence workflow attached to a task so Comp AI can collect recurring proof from connected systems.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await taskAutomationsAutomationsControllerCreateAutomationV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
