/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskAutomationsAutomationsControllerGetAutomationV1 } from "../../funcs/taskAutomationsAutomationsControllerGetAutomationV1.js";
import { AutomationsControllerGetAutomationV1Request$zodSchema } from "../../models/automationscontrollergetautomationv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AutomationsControllerGetAutomationV1Request$zodSchema,
};

export const tool$taskAutomationsAutomationsControllerGetAutomationV1:
  ToolDefinition<typeof args> = {
    name: "get-automation",
    description: `Get automation details

Get automation details in Comp AI. Create, version, run, and inspect automated evidence collection workflows attached to compliance tasks.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await taskAutomationsAutomationsControllerGetAutomationV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
