/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskManagementTaskManagementControllerGetTaskItemsStatsV1 } from "../../funcs/taskManagementTaskManagementControllerGetTaskItemsStatsV1.js";
import { TaskManagementControllerGetTaskItemsStatsV1Request$zodSchema } from "../../models/taskmanagementcontrollergettaskitemsstatsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TaskManagementControllerGetTaskItemsStatsV1Request$zodSchema,
};

export const tool$taskManagementTaskManagementControllerGetTaskItemsStatsV1:
  ToolDefinition<typeof args> = {
    name: "get-task-items-stats",
    description: `Get task items statistics for an entity

Get task items statistics for an entity in Comp AI. Manage task items and attachments linked to operational entities such as risks and vendors.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await taskManagementTaskManagementControllerGetTaskItemsStatsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
