/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { taskAutomationsAutomationsControllerGetTaskAutomationsV1 } from "../../funcs/taskAutomationsAutomationsControllerGetTaskAutomationsV1.js";
import { AutomationsControllerGetTaskAutomationsV1Request$zodSchema } from "../../models/automationscontrollergettaskautomationsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AutomationsControllerGetTaskAutomationsV1Request$zodSchema,
};

export const tool$taskAutomationsAutomationsControllerGetTaskAutomationsV1:
  ToolDefinition<typeof args> = {
    name: "get-task-automations",
    description: `Get all automations for a task

Get all automations for a task in Comp AI. Create, version, run, and inspect automated evidence collection workflows attached to compliance tasks.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await taskAutomationsAutomationsControllerGetTaskAutomationsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
