/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerUpdateFaqsV1 } from "../../funcs/trustPortalTrustPortalControllerUpdateFaqsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$trustPortalTrustPortalControllerUpdateFaqsV1: ToolDefinition =
  {
    name: "update-faqs",
    description: `Update trust portal FAQs

Update trust portal FAQs in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] = await trustPortalTrustPortalControllerUpdateFaqsV1(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
