/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerListVendorsV1 } from "../../funcs/trustPortalTrustPortalControllerListVendorsV1.js";
import { TrustPortalControllerListVendorsV1Request$zodSchema } from "../../models/trustportalcontrollerlistvendorsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustPortalControllerListVendorsV1Request$zodSchema.optional(),
};

export const tool$trustPortalTrustPortalControllerListVendorsV1: ToolDefinition<
  typeof args
> = {
  name: "list-vendors",
  description: `List vendors configured for trust portal

List vendors configured for trust portal in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await trustPortalTrustPortalControllerListVendorsV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
