/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerReorderCustomLinksV1 } from "../../funcs/trustPortalTrustPortalControllerReorderCustomLinksV1.js";
import { TrustPortalControllerReorderCustomLinksV1Request$zodSchema } from "../../models/trustportalcontrollerreordercustomlinksv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustPortalControllerReorderCustomLinksV1Request$zodSchema,
};

export const tool$trustPortalTrustPortalControllerReorderCustomLinksV1:
  ToolDefinition<typeof args> = {
    name: "reorder-custom-links",
    description: `Reorder custom links

Reorder custom links in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustPortalTrustPortalControllerReorderCustomLinksV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
