/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerDenyRequestV1 } from "../../funcs/trustAccessTrustAccessControllerDenyRequestV1.js";
import { TrustAccessControllerDenyRequestV1Request$zodSchema } from "../../models/trustaccesscontrollerdenyrequestv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerDenyRequestV1Request$zodSchema,
};

export const tool$trustAccessTrustAccessControllerDenyRequestV1: ToolDefinition<
  typeof args
> = {
  name: "deny-request",
  description: `Deny Trust Access request

Reject a Trust Center access request with a review reason so customer security access decisions stay auditable.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await trustAccessTrustAccessControllerDenyRequestV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
