/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerGetComplianceResourceUrlV1 } from "../../funcs/trustPortalTrustPortalControllerGetComplianceResourceUrlV1.js";
import { ComplianceResourceSignedUrlDto$zodSchema } from "../../models/complianceresourcesignedurldto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ComplianceResourceSignedUrlDto$zodSchema,
};

export const tool$trustPortalTrustPortalControllerGetComplianceResourceUrlV1:
  ToolDefinition<typeof args> = {
    name: "get-compliance-resource-url",
    description: `Generate a temporary signed URL for a compliance certificate

Generate a temporary signed URL for a compliance certificate in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustPortalTrustPortalControllerGetComplianceResourceUrlV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
