/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerGetSettingsV1 } from "../../funcs/trustPortalTrustPortalControllerGetSettingsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$trustPortalTrustPortalControllerGetSettingsV1:
  ToolDefinition = {
    name: "get-settings",
    description: `Get Trust Center settings

Retrieve Trust Center settings used to configure public status, custom domains, framework visibility, resources, FAQs, and access rules.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] = await trustPortalTrustPortalControllerGetSettingsV1(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
