/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerUpdateCustomFrameworkV1 } from "../../funcs/trustPortalTrustPortalControllerUpdateCustomFrameworkV1.js";
import { TrustPortalControllerUpdateCustomFrameworkV1Request$zodSchema } from "../../models/trustportalcontrollerupdatecustomframeworkv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustPortalControllerUpdateCustomFrameworkV1Request$zodSchema
    .describe(`At least one of \`enabled\` or \`status\` must be provided.`),
};

export const tool$trustPortalTrustPortalControllerUpdateCustomFrameworkV1:
  ToolDefinition<typeof args> = {
    name: "update-custom-framework",
    description:
      `Enable/disable a custom framework on the trust portal and set its status

Enable/disable a custom framework on the trust portal and set its status in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustPortalTrustPortalControllerUpdateCustomFrameworkV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
