/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerResendAccessEmailV1 } from "../../funcs/trustAccessTrustAccessControllerResendAccessEmailV1.js";
import { TrustAccessControllerResendAccessEmailV1Request$zodSchema } from "../../models/trustaccesscontrollerresendaccessemailv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerResendAccessEmailV1Request$zodSchema,
};

export const tool$trustAccessTrustAccessControllerResendAccessEmailV1:
  ToolDefinition<typeof args> = {
    name: "resend-access-email",
    description: `Resend Trust Access email

Resend the access email for an active Trust Access grant so approved reviewers can reopen shared resources.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustAccessTrustAccessControllerResendAccessEmailV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
