/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustPortalTrustPortalControllerUploadTrustDocumentV1 } from "../../funcs/trustPortalTrustPortalControllerUploadTrustDocumentV1.js";
import { UploadTrustDocumentDto$zodSchema } from "../../models/uploadtrustdocumentdto.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UploadTrustDocumentDto$zodSchema,
};

export const tool$trustPortalTrustPortalControllerUploadTrustDocumentV1:
  ToolDefinition<typeof args> = {
    name: "upload-trust-document",
    description: `Upload an additional trust portal document

Upload an additional trust portal document in Comp AI. Configure the live Trust Center, custom domain, public overview, FAQs, compliance resources, documents, links, and vendor disclosures.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustPortalTrustPortalControllerUploadTrustDocumentV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
