/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerListAccessRequestsV1 } from "../../funcs/trustAccessTrustAccessControllerListAccessRequestsV1.js";
import { TrustAccessControllerListAccessRequestsV1Request$zodSchema } from "../../models/trustaccesscontrollerlistaccessrequestsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TrustAccessControllerListAccessRequestsV1Request$zodSchema
    .optional(),
};

export const tool$trustAccessTrustAccessControllerListAccessRequestsV1:
  ToolDefinition<typeof args> = {
    name: "list-access-requests",
    description: `List Trust Access requests

List pending and completed Trust Center access requests so teams can review customer security inquiries through the API.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await trustAccessTrustAccessControllerListAccessRequestsV1(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
