/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trustAccessTrustAccessControllerListGrantsV1 } from "../../funcs/trustAccessTrustAccessControllerListGrantsV1.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$trustAccessTrustAccessControllerListGrantsV1: ToolDefinition =
  {
    name: "list-grants",
    description: `List Trust Access grants

List active, expired, and revoked Trust Access grants for customer security reviews and shared compliance resources.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    tool: async (client, ctx) => {
      const [result] = await trustAccessTrustAccessControllerListGrantsV1(
        client,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
