/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vendorsVendorsControllerGetVendorByIdV1 } from "../../funcs/vendorsVendorsControllerGetVendorByIdV1.js";
import { VendorsControllerGetVendorByIdV1Request$zodSchema } from "../../models/vendorscontrollergetvendorbyidv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VendorsControllerGetVendorByIdV1Request$zodSchema,
};

export const tool$vendorsVendorsControllerGetVendorByIdV1: ToolDefinition<
  typeof args
> = {
  name: "get-vendor-by-id",
  description: `Get vendor details

Retrieve one vendor record with ownership, review status, risk context, and third-party compliance metadata.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vendorsVendorsControllerGetVendorByIdV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
