/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vendorsVendorsControllerUpdateVendorV1 } from "../../funcs/vendorsVendorsControllerUpdateVendorV1.js";
import { VendorsControllerUpdateVendorV1Request$zodSchema } from "../../models/vendorscontrollerupdatevendorv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VendorsControllerUpdateVendorV1Request$zodSchema,
};

export const tool$vendorsVendorsControllerUpdateVendorV1: ToolDefinition<
  typeof args
> = {
  name: "update-vendor",
  description: `Update vendor record

Update vendor ownership, risk attributes, review metadata, and third-party compliance context for an organization.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vendorsVendorsControllerUpdateVendorV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
