/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vendorsVendorsControllerSearchGlobalVendorsV1 } from "../../funcs/vendorsVendorsControllerSearchGlobalVendorsV1.js";
import { VendorsControllerSearchGlobalVendorsV1Request$zodSchema } from "../../models/vendorscontrollersearchglobalvendorsv1op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VendorsControllerSearchGlobalVendorsV1Request$zodSchema.optional(),
};

export const tool$vendorsVendorsControllerSearchGlobalVendorsV1: ToolDefinition<
  typeof args
> = {
  name: "search-global-vendors",
  description: `Search global vendors

Search global vendor records to prefill vendor profiles and speed up third-party risk assessment workflows.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vendorsVendorsControllerSearchGlobalVendorsV1(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
