export const BUTTON_BASE = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '2',
  fontWeight: 'medium',
  transitionProperty: 'background-color, border-color, color, box-shadow, transform',
  transitionDuration: '0.12s',
  transitionTimingFunction: 'ease-out',
  cursor: 'pointer',
  borderRadius: 'input',
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: 'transparent',
  outline: 'none',
  boxShadow: 'sm',
  transform: 'translateY(0)',
  _active: {
    transitionDuration: '0s',
    transform: 'translateY(1px)',
    boxShadow: 'none',
  },
  _focusVisible: {
    borderColor: 'colorPalette.focusRing',
    boxShadow: 'focusRing',
    outline: 'none',
  },
} as const;
