export const semanticColors = {
  bg: { value: { base: '{colors.secondary.50}', _dark: '{colors.secondary.950}' } },
  fg: { value: { base: '{colors.secondary.950}', _dark: '{colors.secondary.50}' } },
  border: { value: { base: '{colors.secondary.200}', _dark: '{colors.secondary.800}' } },
  'border.muted': { value: { base: '{colors.secondary.100}', _dark: '{colors.secondary.900}' } },
  primary: {
    DEFAULT: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.400}' } },
    solid: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.400}' } },
    emphasized: { value: { base: '{colors.primary.800}', _dark: '{colors.primary.500}' } },
    hover: { value: { base: '{colors.primary.800}', _dark: '{colors.primary.500}' } },
    active: { value: { base: '{colors.primary.900}', _dark: '{colors.primary.600}' } },
    subtle: { value: { base: '{colors.primary.50}', _dark: '{colors.primary.900}' } },
    muted: { value: { base: '{colors.primary.100}', _dark: '{colors.primary.800}' } },
    fg: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.300}' } },
    contrast: { value: { base: 'white', _dark: 'black' } },
    border: { value: { base: '{colors.primary.300}', _dark: '{colors.primary.700}' } },
    focusRing: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.400}' } },
  },
  secondary: {
    DEFAULT: { value: { base: '{colors.secondary.100}', _dark: '{colors.secondary.800}' } },
    solid: { value: { base: '{colors.secondary.800}', _dark: '{colors.secondary.200}' } },
    emphasized: { value: { base: '{colors.secondary.900}', _dark: '{colors.secondary.300}' } },
    hover: { value: { base: '{colors.secondary.900}', _dark: '{colors.secondary.300}' } },
    active: { value: { base: '{colors.secondary.950}', _dark: '{colors.secondary.400}' } },
    subtle: { value: { base: '{colors.secondary.50}', _dark: '{colors.secondary.900}' } },
    muted: { value: { base: '{colors.secondary.100}', _dark: '{colors.secondary.800}' } },
    fg: { value: { base: '{colors.secondary.900}', _dark: '{colors.secondary.100}' } },
    contrast: { value: { base: 'white', _dark: 'black' } },
    border: { value: { base: '{colors.secondary.300}', _dark: '{colors.secondary.700}' } },
    focusRing: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.400}' } },
  },
  blue: {
    solid: { value: { base: '{colors.blue.700}', _dark: '{colors.blue.400}' } },
    emphasized: { value: { base: '{colors.blue.800}', _dark: '{colors.blue.500}' } },
    hover: { value: { base: '{colors.blue.800}', _dark: '{colors.blue.500}' } },
    active: { value: { base: '{colors.blue.900}', _dark: '{colors.blue.600}' } },
    subtle: { value: { base: '{colors.blue.50}', _dark: '{colors.blue.900}' } },
    muted: { value: { base: '{colors.blue.100}', _dark: '{colors.blue.800}' } },
    fg: { value: { base: '{colors.blue.700}', _dark: '{colors.blue.300}' } },
    contrast: { value: { base: 'white', _dark: 'black' } },
    border: { value: { base: '{colors.blue.300}', _dark: '{colors.blue.700}' } },
    focusRing: { value: { base: '{colors.blue.700}', _dark: '{colors.blue.400}' } },
  },
  orange: {
    solid: { value: { base: '{colors.orange.700}', _dark: '{colors.orange.400}' } },
    emphasized: { value: { base: '{colors.orange.800}', _dark: '{colors.orange.500}' } },
    hover: { value: { base: '{colors.orange.800}', _dark: '{colors.orange.500}' } },
    active: { value: { base: '{colors.orange.900}', _dark: '{colors.orange.600}' } },
    subtle: { value: { base: '{colors.orange.50}', _dark: '{colors.orange.900}' } },
    muted: { value: { base: '{colors.orange.100}', _dark: '{colors.orange.800}' } },
    fg: { value: { base: '{colors.orange.700}', _dark: '{colors.orange.300}' } },
    contrast: { value: { base: 'white', _dark: 'black' } },
    border: { value: { base: '{colors.orange.300}', _dark: '{colors.orange.700}' } },
    focusRing: { value: { base: '{colors.orange.700}', _dark: '{colors.orange.400}' } },
  },
  rose: {
    solid: { value: { base: '{colors.rose.700}', _dark: '{colors.rose.400}' } },
    emphasized: { value: { base: '{colors.rose.800}', _dark: '{colors.rose.500}' } },
    hover: { value: { base: '{colors.rose.800}', _dark: '{colors.rose.500}' } },
    active: { value: { base: '{colors.rose.900}', _dark: '{colors.rose.600}' } },
    subtle: { value: { base: '{colors.rose.50}', _dark: '{colors.rose.900}' } },
    muted: { value: { base: '{colors.rose.100}', _dark: '{colors.rose.800}' } },
    fg: { value: { base: '{colors.rose.700}', _dark: '{colors.rose.300}' } },
    contrast: { value: { base: 'white', _dark: 'black' } },
    border: { value: { base: '{colors.rose.300}', _dark: '{colors.rose.700}' } },
    focusRing: { value: { base: '{colors.rose.700}', _dark: '{colors.rose.400}' } },
  },
  yellow: {
    // Yellow in our brand palette is a light, sand-y accent (#FFD2A6 at 500).
    // Treat it as a light palette: black text + small darker deltas on hover/active.
    solid: { value: { base: '{colors.yellow.500}', _dark: '{colors.yellow.400}' } },
    emphasized: { value: { base: '{colors.yellow.600}', _dark: '{colors.yellow.500}' } },
    hover: { value: { base: '{colors.yellow.600}', _dark: '{colors.yellow.500}' } },
    active: { value: { base: '{colors.yellow.700}', _dark: '{colors.yellow.600}' } },
    subtle: { value: { base: '{colors.yellow.50}', _dark: '{colors.yellow.900}' } },
    muted: { value: { base: '{colors.yellow.100}', _dark: '{colors.yellow.800}' } },
    fg: { value: { base: '{colors.yellow.800}', _dark: '{colors.yellow.300}' } },
    contrast: { value: { base: 'black', _dark: 'black' } },
    border: { value: { base: '{colors.yellow.300}', _dark: '{colors.yellow.700}' } },
    focusRing: { value: { base: '{colors.yellow.700}', _dark: '{colors.yellow.400}' } },
  },
  sand: {
    // Sand is also a light palette → black text + small darker deltas.
    subtle: { value: { base: '{colors.sand.50}', _dark: '{colors.sand.900}' } },
    muted: { value: { base: '{colors.sand.100}', _dark: '{colors.sand.800}' } },
    fg: { value: { base: '{colors.sand.900}', _dark: '{colors.sand.100}' } },
    solid: { value: { base: '{colors.sand.500}', _dark: '{colors.sand.300}' } },
    emphasized: { value: { base: '{colors.sand.600}', _dark: '{colors.sand.400}' } },
    hover: { value: { base: '{colors.sand.600}', _dark: '{colors.sand.400}' } },
    active: { value: { base: '{colors.sand.700}', _dark: '{colors.sand.500}' } },
    contrast: { value: { base: 'black', _dark: 'black' } },
    border: { value: { base: '{colors.sand.300}', _dark: '{colors.sand.700}' } },
    focusRing: { value: { base: '{colors.primary.700}', _dark: '{colors.primary.400}' } },
  },
} as const;
