/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export interface Env {
  COMPAI_APIKEY?: string | undefined;

  COMPAI_DEBUG?: boolean | undefined;
}

export const envSchema: z.ZodType<Env> = z.object({
  COMPAI_APIKEY: z.string().optional(),

  COMPAI_DEBUG: z.coerce.boolean().optional(),
});

let envMemo: Env | undefined = undefined;
/**
 * Reads and validates environment variables.
 */
export function env(): Env {
  if (envMemo) {
    return envMemo;
  }

  const globals = globalThis as {
    process?: { env?: Record<string, string | undefined> };
    Deno?: { env?: { toObject?: () => Record<string, string | undefined> } };
  };

  envMemo = envSchema.parse(
    globals.process?.env ?? globals.Deno?.env?.toObject?.() ?? {},
  );
  return envMemo;
}

/**
 * Clears the cached env object. Useful for testing with a fresh environment.
 */
export function resetEnv() {
  envMemo = undefined;
}
