version: '3.7'

services:
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=comp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d comp']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: '10m'
        max-file: '3'

networks:
  prisma-network:

volumes:
  postgres_data:
