name: Deploy to Trigger.dev (dev)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Updated to match Node.js w/ Vercel
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Clear cache
        run: rm -rf node_modules .bun
      - name: Install dependencies
        run: bun install
      - name: Install DB package dependencies
        working-directory: ./packages/db
        run: bun install
      - name: Generate Prisma client
        working-directory: ./packages/db
        run: bunx prisma generate
      - name: 🚀 Deploy Trigger.dev
        working-directory: ./apps/app
        timeout-minutes: 20
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: bunx trigger.dev@4.0.0 deploy --env staging --log-level debug
