name: Deploy to Trigger.dev (dev)
on:
  push:
    branches:
      - main

permissions:
  contents: read # only needs to check out the repo to build & deploy

jobs:
  deploy:
    runs-on: warp-ubuntu-latest-arm64-4x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Updated to match Node.js w/ Vercel
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Clear cache
        run: rm -rf node_modules
      - name: Install dependencies
        run: npm ci || npm ci --ignore-scripts
      - name: Build DB package
        working-directory: ./packages/db
        run: npm run build
      - name: Build Integration Platform package
        working-directory: ./packages/integration-platform
        run: npm run build
      - name: Generate Prisma clients
        run: |
          cd packages/db && node scripts/generate-prisma-client-js.js
          cd ../..
          cd apps/app && mkdir -p prisma/schema
          find ../../packages/db/prisma/schema -name '*.prisma' ! -name 'schema.prisma' -exec cp {} prisma/schema/ \;
          npx prisma generate --schema=prisma/schema
      - name: 🚀 Deploy Trigger.dev
        working-directory: ./apps/app
        timeout-minutes: 20
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
        run: npx trigger.dev@4.4.3 deploy --env staging --log-level debug
